### ISSUE TITLE
Cant verfiy account because of winebrowser (CONNECTION REFUSED) (CONNECTION RESET BY PEER)

### ISSUE THREAD

**Issue by catlomao** [NelloKudo/osu-winello#104]
hello i found a bug and i fixed it myself so i wanna share how i did it

here
https://github.com/catlomao/fixwinebrowser/
just go README.md

enjoy :3

**Comment by catlomao** [comment]
the source code is open and in "source-code.py" you can build or pkg it yourself if you want!

**Comment by kartavkun** [comment]
That's good if you found the fix for the bug, but...
what the bug? what the file is fixing?

**Comment by Sclafus** [comment]
Care to explain what you are trying to fix? winello should open your default browser iirc.

**Comment by catlomao** [comment]
the bug or to be more specific the problem with winebrowser if you just installed osu!(osu-winello) and you trying to log in, winebrowser will not work or refuses to redirect to the log in page so you can verify your account , i tried to fix it myself and here is the fix i made

**Comment by catlomao** [comment]
I have no idea if this is only me or it does not work on mine but if someone had the same bug with wine they can fix it now.

**Comment by kartavkun** [comment]
You just needed `xdg-utils, xdg-desktop-portal and xdg-desktop-portal-gtk` packages

https://github.com/NelloKudo/osu-winello/issues/92

**Comment by catlomao** [comment]
it still wont open and yes i did install these packages (reinstall)
023c:err:environ:init_peb starting L"C:\\windows\\syswow64\\winebrowser.exe" in experimental wow64 mode
[4246:4246:1012/111530.038655:ERROR:socket.cc(120)] recvmsg: Connection reset by peer (104)

**Comment by catlomao** [comment]
do i reinstall or what do i do

**Comment by catlomao** [comment]
nvm everything worked after switching from gnome to kde plasma (wayland)
