### ISSUE TITLE
Script failed: Download failed, check your connection or open an issue here:

### ISSUE THREAD

**Issue by sleepingzzs** [NelloKudo/osu-winello#11]
Followed every step then ran './osu-winello.sh' and got this error. Tried re running the command multiple times but got the same results also my internet connection is fine.
![image](https://user-images.githubusercontent.com/93027509/195998493-09f2feb0-fb42-4920-8d4c-a9bbc1d9fee7.png)

**Comment by NelloKudo** [comment]
I just tried running the script again and downloads seem to be working, maybe GitHub was down for a second there? Try again now

**Comment by sleepingzzs** [comment]
> I just tried running the script again and downloads seem to be working, maybe GitHub was down for a second there? Try again now

yep it worked now it was probably down
but now im here.. 
![image](https://user-images.githubusercontent.com/93027509/196485084-cda79fbf-b0f7-4e52-86ec-696b4837193d.png)

**Comment by sleepingzzs** [comment]
i think now osu! is down? cuz it kept loading when i tried to install the exe from the website

**Comment by NelloKudo** [comment]
This really looks like an issue with your connection somehow, it won’t download even on other github links apparently. Try setting your DNS to Google ones (8.8.8.8 or 8.8.4.4)

**Comment by sleepingzzs** [comment]
> This really looks like an issue with your connection somehow, it won’t download even on other github links apparently. Try setting your DNS to Google ones (8.8.8.8 or 8.8.4.4)

Thanks it worked :)
