### ISSUE TITLE
Error on installing...

### ISSUE THREAD

**Issue by Lupahlinda** [NelloKudo/osu-winello#112]
so, i installed osu before on this machine and it worked, but while i was deleting some wine prefixes, i accidentally deleted the osu prefix files and since then i haven't been able to install osu again...

(When I tried to reinstall it, it tells to uninstall Winello, but when I use osu-wine --remove, dont do a single thing)
![image](https://github.com/user-attachments/assets/47b715f0-6b4c-4efa-b0b6-da7279f7038e)

I also tried to search the files, fixfolders, fixprefix, recreate the folders manually, delete what remained, nothing works

**Comment by NelloKudo** [comment]
Running `rm ~/.local/bin/osu-wine` should be enough when that happens  🏄🏻 

I'll also soon push the script back to Proton since we fixed the issue with last update, so if the legacy branch still gives issues, please switch to it! 🥳
