### ISSUE TITLE
Sound error!!!

### ISSUE THREAD

**Issue by Lupahlinda** [NelloKudo/osu-winello#113]
I had this sound error sometimes but never knew what was the cause, it cant process sound right and become a mess of audio... I'm curious to know why it happens (also happens when I used pipewire too, I cant use pipewire now on arch because it breaks pavucontrol for me)

**Comment by NelloKudo** [comment]
The Proton build is supposed to work with PipeWire though, which is pretty much every distro's standard as of today. If you had issues with pavucontrol, make sure you also have `pipewire-pulse` and `wireplumber` installed, or read the Wiki's section on Installing Pipewire!
