### ISSUE TITLE
Unplugging mouse or dongle crashes osu!

### ISSUE THREAD

**Issue by asdfoiua** [NelloKudo/osu-winello#114]
I'm using EndeavourOS with KDE Plasma on X11. I have an NVIDIA 2080 super GPU. I had to reinstall osu-wine to fix the issue that happened recently, and after doing so and using `--changedir` to change it to my old install this issue started happening. I use a Logitech G Pro Superlight, and when I unplugged it from charging it crashed the game. The same thing happens I unplug the dongle when it's being used wirelessly. I use solaar to change settings, and set the DPI and polling rate, but even if I close it the issue still happens. 

```
X Error of failed request:  XI_BadDevice (invalid Device parameter)
  Major opcode of failed request:  131 (XInputExtension)
  Minor opcode of failed request:  3 (X_OpenDevice)
  Device id in failed request: 0x5a00001
  Serial number of failed request:  125
  Current serial number in output stream:  125
X Error of failed request:  XI_BadDevice (invalid Device parameter)
  Major opcode of failed request:  131 (XInputExtension)
  Minor opcode of failed request:  3 (X_OpenDevice)
  Device id in failed request: 0x166
  Serial number of failed request:  1410
  Current serial number in output stream:  1410
X Error of failed request:  XI_BadDevice (invalid Device parameter)
  Major opcode of failed request:  131 (XInputExtension)
```

This is what  I get when running osu-wine through terminal. Sorry if the formatting is wrong, I'm not sure the proper way to post a bug report or if this is even the correct place for this.

**Comment by kartavkun** [comment]
Use [piper](https://github.com/libratbag/piper) for changing settings for mouse
