### ISSUE TITLE
No audio

### ISSUE THREAD

**Issue by Lyall-A** [NelloKudo/osu-winello#117]
ever since osu broke the other day i havent had any audio, i can see the output bar on pavucontrol but it is outputting to "unknown output"
also, when i turn off audio compatibility i get my ears blown for a split second. changing output source to anything other than default completely breaks the game
im probably being dumb but help appreciated

https://github.com/user-attachments/assets/b0712eab-64fa-4d28-a885-7f72db94f685

**Comment by kartavkun** [comment]
Have you tried turn on audio compability mode? Also are you using pipewire or pulseaudio?

**Comment by kartavkun** [comment]
Can you change the output for osu! from pavucontrol?

**Comment by kartavkun** [comment]
Take a pipewire and wireplumber configs from [my repo](https://github.co/kartavkun/arch-osu-wine) and the restart pipewire(check README in the same repo)

**Comment by Lyall-A** [comment]
thanks, changing output from pavucontrol didnt help but i can try ur configs later. just weird how it randomly broke after i updated osu-wine for the first time in months, maybe something to do with a update to the script? idk

**Comment by Lyall-A** [comment]
i just fixed this by changing default.clock.quantum from 1024 to 512 in pipewire config, so its all good now but idk how this problem randomly started happening when it was just fine previously

**Comment by kartavkun** [comment]
I always set `default.clock.quantum` value to 64 for low latency, bc osu! is a rhythm game and low audio latency is needed in my opinion. Or 128 if CPU is not that good for that

**Comment by Lyall-A** [comment]
thanks ill try 64 then, wtf does this even do/mean

**Comment by Lyall-A** [comment]
lmao both 64 and 128 sound like there is demons in my laptop, 512 is all good i dont seem to notice the latency and it doesnt really bother me
