### ISSUE TITLE
Bad FPS after install

### ISSUE THREAD

**Issue by curtime** [NelloKudo/osu-winello#12]
I don't know if this is the proper place to open this issue however after installing I'm getting 65FPS on the main menu, with a 3060Ti and 3700x, I'm using arch linux my drivers are installed I updated my system as well. I'm not sure where to start troubleshooting this. Any input is greatly appreciated!

**Comment by NelloKudo** [comment]
Hi! Can you start by telling me your PC’s specs? For example if it’s a laptop or a desktop e.e

Also try installing the following:
`sudo pacman -S lib32-nvidia-utils`

**Comment by curtime** [comment]
Installing that package fixed it, I recently reinstalled and I must've forgot it thank you so much!!
