### ISSUE TITLE
New osu! update crashed the game on launch.

### ISSUE THREAD

**Issue by UnitieG** [NelloKudo/osu-winello#122]
Basically, The client updated itself. And that cause the game to not startup.

When I got it working by running osu! directly from wine and letting it update. I launch osu! again using osu-wine.
When It's patching, The game crashed and no longer launches.

**Comment by Akosih97** [comment]
I have the same problem.

**Comment by NelloKudo** [comment]
The issue was mentioned a lot already in the last few issues, I recommend checking them out for more xd

Fix is to simply update to latest Proton with `osu-wine --update` and delete `WINE_BLOCK_GET_VERSION` from ~/.local/bin/osu-wine

**Comment by UnitieG** [comment]
I'll try this real quick

**Comment by UnitieG** [comment]
> The issue was mentioned a lot already in the last few issues, I recommend checking them out for more xd
> 
> Fix is to simply update to latest Proton with `osu-wine --update` and delete `WINE_BLOCK_GET_VERSION` from ~/.local/bin/osu-wine

Thank you so much, This actually fixed the problem that I was having. Thank you so much!
