### ISSUE TITLE
osu is NOT launching

### ISSUE THREAD

**Issue by EnderGuest** [NelloKudo/osu-winello#123]
So, recently there has been a issue with people's games (issue #109) and I have switched to the legacy branch because it is a temproary fix for it (I am pretty sure I did everything correct.) but NO NO, it just doesn't wan't to launch. It's also a new, fresh install (I have deleted the old one.) anyways, this is what I get on the terminal when I launch osu using **osu-wine**:
```
002c:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -a -r" (126).
wine: failed to open "/osu!/osu!.exe": c0000135
```
I have tried checking if osu!.exe is marked as executable and changed the windows versions on wine to see if anything gets fixed but little to no luck, it just WON'T launch, giving me the same error that makes me feel a sense of dread that I will be stuck playing osu!lazer for the rest of my life. SOO yeah, it would be great if anyone could atleast help or point out a hint to the issue itself.

**Comment by NelloKudo** [comment]
The Proton (main) branch is now working fine, so you should switch to that. Anyways, where are you installing the game? Pretty sure I saw that issue when you’re launching the game on a disk without write/read permissions.

Try these options and see i guess!

**Comment by EnderGuest** [comment]
I installed the game on my 1 TB HDD (NOT MAIN.) and wait actually, let me check if I have write/read perms.

**Comment by EnderGuest** [comment]
Ah, switching to the proton branch fixed everything. Thank you so much!! I can now finally play osu!stable
