### ISSUE TITLE
Prime-run not working

### ISSUE THREAD

**Issue by takaagry** [NelloKudo/osu-winello#124]
Hi, I just want to give something I just found few minutes ago when I'm trying to monitoring my GPU.

First, this is my system information that I use for running osu-winello

CPU: 11th Gen Intel i5-11400H
GPU: Intel TigerLake-H GT1 [UHD Graphics]
GPU: NVIDIA GeForce GTX 1650 Mobile / Max-Q
Model: MSI GF63 Thin 11SC (muxless)

OS: EndeavourOS Linux x86_64
Kernel: 6.11.6-arch1-1
Shell: bash 5.2.37
DE: Plasma 6.2.3
WM: kwin 6.1.2-1
Wayland

I just found out that the osu-winello wont run on **nvidia (prime-run)** even after forced it using terminal (**prime-run osu-wine**). I've tried using terminal and edit the desktop file and both wont work either. I've tried to run **osu! lazer** using **prime-run** and it works, so I assume its the **osu-winello**.

I dont know if this related to the latest update that broke the osu-winello or this just recent happen or this just me messing up my setting. I'll try to reinstall after this and give some update later.

Hope this help. Have a nice day. Thank you.

**Comment by kartavkun** [comment]
use MANGOHUD for monitoring lol

**Comment by kartavkun** [comment]
also osu! stable sucks on Wayland, use Xorg

**Comment by takaagry** [comment]
Hi, I want to give some update.

I've tried testing using both Wayland and X11 and for both the newest version as I write this and the version before (where the boss key and font bugged).

All the test done by running the osu-wine using **prime-run** terminal command (**prime-run osu-wine**) and using **nvtop** for checking if the app running on **nvidia** or not.

The result I got from the test is
1. Using the **previous osu-wine** on **Wayland**, the game still not run on nvidia
2. Using the **previous osu-wine** on **X11**, the game still not run on nvidia
3. Using the **newest version** on **Wayland**, the same still not run on nvidia
4. Using the **newest version** on **X11**, the same still not run on nvidia

Another thing I want to add is when on **X11**, I can't run any app on **prime-run** but on **wayland** I can run **prime-run** but not the **osu-wine**.

Also, since few days ago I'm trying to change my nvidia driver to nvidia-dkms, I think this has some correlation. I will try to reinstall the normal nvidia driver and see if that will change the prime-run behavior. If this not working maybe I'll try to reinstall the whole OS again and see if that also fix (since lately I've been messing around with my OS and system).

If I found the fix, either from the reinstall or other things, I will give some update and close this issue.

Thank you.

**Comment by takaagry** [comment]
First I'm sorry, tbh I still don't really understand linux that much and for the prime-run, what I know is prime-run is script that makes the app I want to use run on my dGPU or nvidia.

The problem I got is for the **osu-wine**the app forced to use iGPU even after running it using the script. I don't get any error messages like on the nvidia forum. 

Like what I said above, I think this has something to do with me messing around with my system and if that the case, I'll give some update. Sorry for causing the confusion and inconvenience.

Thank you.

**Comment by takaagry** [comment]
> Does your problem still happen if you remove the line that has `export PROTON_USE_WINED3D=...` in your `~/.local/bin/osu-wine` file? This was put there to work around an issue with the previous Proton version, but it shouldn't be necessary anymore. The `osu-wine --update` command doesn't update the `osu-wine` launch script itself, so it might still be there if you didn't clean install from the last Proton version.

I've check the file and there's no `export PROTON_USE_WINED3D=...` on `osu-wine` file.

**Comment by takaagry** [comment]
Hi, I want to give some update.

I've tired to reinstall all my driver (both **Intel** and **Nvidia**) with the **[Installing Drivers](https://github.com/lutris/docs/blob/master/InstallingDrivers.md)** on the main page and now everything works fine again. 

I believe the cause of this is not the osu-wine it self but rather when I tried to change nvidia driver to **nvidia-dkms** using **nvidia-inst**. Because of this, I believe some essential packages that require to run **osu-wine** on nvidia was removed (like lib32 package) thus the **osu-wine** can't run under or using nvidia. And maybe why other app can run using **nvidia** or **prime-run** is because the packages or driver needed for the app to run is already installed.

![Screenshot_20241108_091621](https://github.com/user-attachments/assets/d9d6f7c6-0336-4f07-b104-dd5eb8d4759b)
0 is Nvidia and 1 is Intel.

I want to thank you for helping me with this and apologize for causing the problem, confusion and inconvenience. All of this is my own fault and with this I will close this issue.

Thank you and have a nice day.
