### ISSUE TITLE
add `zstd` as a dependency for other linux distros (Void Linux, etc)

### ISSUE THREAD

**Issue by pinitik1906** [NelloKudo/osu-winello#125]
after installing with osu-winello.sh, then i open with `osu-wine` in my terminal, it says that i had to install `zstd` to make steamrt to work for proton-osu.

it did not open without it. so i install `zstd`, osu just opens normally and working properly without any issues.

distro: (Void Linux x86_64 glibc)

**Comment by NelloKudo** [comment]
That's strange though, since the bundled umu-run should already have zstd in it...

Could you try updating to the latest proton version with `osu-wine --update` and seeing if it still happens?
You'll probably have to temporarily remove zstd from your distro to test though xD
