### ISSUE TITLE
Can't connect to bancho.

### ISSUE THREAD

**Issue by UnitieG** [NelloKudo/osu-winello#126]
Basically, I didn't use my pc for 2 days and osu! broke. I fixed it with ``osu-wine --fixprefix``. And I realized that I can't connect to bancho.
![ai0sjfiasfjaiosfjaios](https://github.com/user-attachments/assets/0871ab37-1dd0-4b19-b65b-f45eab32b70a)

**Comment by NelloKudo** [comment]
Closing since reinstalling Winello fixed it!
