### ISSUE TITLE
osu-winello refuses to install without "Package steam"

### ISSUE THREAD

**Issue by Shrad3n** [NelloKudo/osu-winello#128]
For some reason, running the script always gives me this issue and I am unsure of how to have it work.

All packages are up to date.
Winello: Ubuntu/Debian-based distro detected..
Winello: Please insert your password to install dependencies!
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package steam is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  steam-installer steam-devices

E: Package 'steam' has no installation candidate
Script failed: Dependencies install failed, check apt or your connection..
Reverting install...:
Reverting done, try again with ./osu-winello.sh

**Comment by NelloKudo** [comment]
Just replace the line in the script which has “steam” with “steam-installer” and it should work. Lmk!
