### ISSUE TITLE
cant launch osu

### ISSUE THREAD

**Issue by deridray** [NelloKudo/osu-winello#129]
this happens when trying to launch osu-wine via terminal:

[deridray@owo ~]$ osu-wine
umu-launcher version 1.1.3 (3.13.0 (main, Oct 16 2024, 03:24:23) [Clang 14.0.3 ])
steamrt is up to date
ProtonFixes[142514] INFO: Running protonfixes
ProtonFixes[142514] INFO: Running checks
ProtonFixes[142514] INFO: All checks successful
ProtonFixes[142514] WARN: Game title not found in CSV
ProtonFixes[142514] INFO: Non-steam game UNKNOWN (umu-727)
ProtonFixes[142514] INFO: No store specified, using UMU database
ProtonFixes[142514] INFO: Using global defaults for UNKNOWN (umu-727)
ProtonFixes[142514] INFO: Non-steam game UNKNOWN (umu-727)
ProtonFixes[142514] INFO: No store specified, using UMU database
ProtonFixes[142514] INFO: No global protonfix found for UNKNOWN (umu-727)
Proton: /home/osu!/osu!.exe
Proton: Executable a unix path, launching with /unix option.
fsync: up and running.
notice: didn't have realtime permissions to change priority to SCHED_FIFO/55
002c:fixme:winediag:loader_init wine-staging 9.0 is a testing version containing experimental patches.
002c:fixme:winediag:loader_init Please mention your exact version when filing bug reports on winehq.org.
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0034:err:service:process_send_command receiving command result timed out
0034:fixme:service:scmdatabase_autostart_services Auto-start service L"winebus" failed to start: 1053
0034:err:service:process_send_command receiving command result timed out
0034:fixme:service:scmdatabase_autostart_services Auto-start service L"wineusb" failed to start: 1053
0034:err:service:process_send_start_message service L"PlugPlay" failed to start
0034:fixme:service:scmdatabase_autostart_services Auto-start service L"PlugPlay" failed to start: 1053
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
00d8:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
00d8:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 7B883241, 28) stub
Command exited with status: 0

how to fix this?

**Comment by NelloKudo** [comment]
try `osu-wine --winecfg` and setting Windows version to some recent one (8.1, 10 etc)

**Comment by deridray** [comment]
nothing
![image](https://github.com/user-attachments/assets/e1e13f74-01ef-4192-aefa-b45331b698df)

**Comment by deridray** [comment]
and how to set windows version to earlier?

**Comment by NelloKudo** [comment]
`osu-wine --winecfg` and you can change Windows versions from there. But a reinstall would probably fix it.
