### ISSUE TITLE
Script fails to download a dead Dropbox link for wine-osu

### ISSUE THREAD

**Issue by izsFree** [NelloKudo/osu-winello#13]
The script fails to continue the installation process thanks to one of the nescessary links going out:
![Captura desde 2022-11-19 22-42-26](https://user-images.githubusercontent.com/118642211/202878846-a34a53f7-683b-4ffb-95e8-36dc10e09bcd.png)

I attempted to get wget to grab gonX's wine-osu but google drive is weird and I couldn't figure it out.

Quick workaround was to just edit the 6th line on the script, replacing the Glibc version check to an "old" version and use the system's Wine install, which works for me on Fedora 37 but probably won't on the debian/ubuntu/mint people with no-so-recent versions of Wine.

**Comment by NelloKudo** [comment]
You only need to git clone the repo again, as that version seems to be a bunch of commits behind (repo is now using GitHub for downloads and Wine 7.20)

**Comment by izsFree** [comment]
Well now I know I have to update repos before opening issues, my bad!

**Comment by NelloKudo** [comment]
> Well now I know I have to update repos before opening issues, my bad!

Nah it's fine to be fair, I'll implement a way to grab the link directly from the repo in the near future xD
