### ISSUE TITLE
How do i map?

### ISSUE THREAD

**Issue by RambilE** [NelloKudo/osu-winello#135]
I'm trying to drag and drop an mp3 into the "Drop an mp3 file here and start mapping" box and it doesn't work?

Some info:
WM: hyprland
File manager: Thunar
I used the latest version of install script
I tried to open file with osu! from file manager (there were three different osu! icons and i've tried them all)

Drag and drop definetely works with thunar because i can drop files in my browser and other thunar windows

**Comment by JizzyOnGithub** [comment]
I have a problem like this. If you have two monitors, try putting osu on your other display then dragging it.

**Comment by NelloKudo** [comment]
I use bspwm and dragging mp3s works fine though and since it doesn't even work on Lazer (which is native) it's probably an hyprland thing..

Have you tried out other WM/DEs? There's probably some workaround for it to work on hyprland but I don't use it :/
