### ISSUE TITLE
Unable to use physical buttons on Steam Deck while osu! window is active

### ISSUE THREAD

**Issue by diponski3** [NelloKudo/osu-winello#136]
Hi first time posting here. Today I finally managed to install osu! on my SD after it being broken after an update. Everything installed smoothly and I managed to get into the game, but another problem appeared. Game only reacts to touchscreen. Outside of that, no physical button works, that includes trackpad for a mouse fuction, and most importantly I can't open up the virtual keyboard (with Steam+X shortcut). Help would be appreciated :) Thanks

**Comment by NelloKudo** [comment]
Closing this as the fix was to run osu! through Steam (looks like Steam Input did some magic there).
