### ISSUE TITLE
Chat links, shift+f12 and "open osu! folder" have stopped working

### ISSUE THREAD

**Issue by greatelmo** [NelloKudo/osu-winello#137]
What the title says, and previous installs worked but now they don't.
This isn't a browser issue as Firefox is my only and default browser. 

Is there a fix coming?

**Comment by NelloKudo** [comment]
It’s probably an issue on your install though, they work fine here. Have you tried remaking your prefix already? `osu-wine --fixprefix`

Also if your links aren’t opening, look for logs in chat once you open them. Something will be arguing about it there.

**Comment by greatelmo** [comment]
I found a fix.

I just had to install xdg-utils xdg-desktop-portal xdg-desktop-portal-gtk and it's fine now.
I tried that before with no effect.

**Comment by NelloKudo** [comment]
Yeah that’s in dependencies indeed, glad it works! Closing 👍🏻
