### ISSUE TITLE
Osu Winello won't install at all

### ISSUE THREAD

**Issue by fanqyxl** [NelloKudo/osu-winello#151]
![image](https://github.com/user-attachments/assets/c61c17ad-1542-46b6-9097-828e924a22f2)
It also thinks im using ubuntu/debian, when im on arch. Any fix? I have installed all nessesery dependensices

**Comment by NelloKudo** [comment]
Either uninstall `apt` from your system or delete lines with `apt install` in the script. Somehow apt gets installed in Arch for... no reason xd

**Comment by fanqyxl** [comment]
OMFG TYSM THAT FIXED IT

**Comment by NelloKudo** [comment]
Glad it works! I'll find a better workaround someday. Also nice rice ;)
