### ISSUE TITLE
Importing a map makes the game not register keybord input

### ISSUE THREAD

**Issue by chicco-carone** [NelloKudo/osu-winello#17]
Every time i want to import a map that i downloaded after i import it the game stops registering keyboard input and i have to open task manager or alt+tab a lot of times to until the game gets minimized and when it gets minimized i can open it again and it works. sometimes this just kills the entire os and i can only restart.

system information pulled from lutris
System]
OS:              Arch Linux rolling n/a
Arch:            x86_64
Kernel:          6.1.1-xanmod1-linux-xanmod
Desktop:         KDE
Display Server:  x11

[CPU]
Vendor:          GenuineIntel
Model:           11th Gen Intel(R) Core(TM) i5-11600K @ 3.90GHz
Physical cores:  6
Logical cores:   12

[Memory]
RAM:             15.5 GB
Swap:            4.0 GB

[Graphics]
Vendor:          NVIDIA Corporation
OpenGL Renderer: NVIDIA GeForce RTX 2060/PCIe/SSE2
OpenGL Version:  4.6.0 NVIDIA 525.78.01
OpenGL Core:     4.6.0 NVIDIA 525.78.01
OpenGL ES:       OpenGL ES 3.2 NVIDIA 525.78.01
Vulkan:          Supported

**Comment by NelloKudo** [comment]
The video below will show everything itself, but as you can see that's not an issue related to the script or to Wine, it's rather a **KDE problem** with how it handles windows and stuff. 

Video shows examples with respectively GNOME, XFCE and KDE, all on a fresh Arch Linux install. The only solution I can recommend is to alt-tab correctly to osu! before using keyboard. Not a KDE user here :/

Anyways, here's the link: https://youtu.be/YZICGeOc6z8

**Comment by chicco-carone** [comment]
Do you know if it's an issue with x11 so wayland can fix it or it's just kde?
