### ISSUE TITLE
404 when trying to update game

### ISSUE THREAD

**Issue by Quicksoapy** [NelloKudo/osu-winello#20]
The script tries to wget the following file: https://www.dropbox.com/s/raw/xvuub4efldyjsj4/wine-osu-7.18-x86_64.tar.xz

this returns 404

pls fix i wanna play

**Comment by NelloKudo** [comment]
Update works fine but you're probably on an old version of the script, please consider git cloning it again before using update again. Anyways, do the following and you'll play just fine:

wget -O wine-osu-8.0-rc4-x86_64.tar.xz https://github.com/NelloKudo/WineBuilder/releases/download/wine-osu8.0/wine-osu-8.0-rc4-x86_64.tar.xz
tar -xf wine-osu-8.0-rc4-x86_64.tar.xz
rm -rf ~/.local/share/osuconfig/wine-osu
mv wine-osu ~/.local/share/osuconfig/
