### ISSUE TITLE
winetricks has no installation candidate and unable to locate package steam?

### ISSUE THREAD

**Issue by soliwoli** [NelloKudo/osu-winello#24]
it tells me that so it reverts the install

**Comment by NelloKudo** [comment]
I need some more info about that. What distro are you using first of all? A distro for gaming without Steam and Winetricks seems kinda sus to me.

**Comment by soliwoli** [comment]
i use debian
i wiped all my files (sudo rm rf) on accident

**Comment by NelloKudo** [comment]
> i use debian
> i wiped all my files (sudo rm rf) on accident

Then I’d probably consider a reinstall 💀

**Comment by soliwoli** [comment]
i did

**Comment by azu0609** [comment]
I believe this is a issue of this script. Script uses add-apt-repository on dependencies install part but which requires software-properties-common and it is not installed by default on Debian. Also steam and winetricks is not on default Debian repository (I think), so this cause unable to locate package

**Comment by NelloKudo** [comment]
> I believe this is a issue of this script. Script uses add-apt-repository on dependencies install part but which requires software-properties-common and it is not installed by default on Debian. Also steam and winetricks is not on default Debian repository (I think), so this cause unable to locate package

Yep I just checked online too, I guess I’ll need to test Debian a bit. Fixing in the next days 👍

**Comment by NelloKudo** [comment]
Fixed with [latest commit](https://github.com/NelloKudo/osu-winello/commit/518fee5dfbb7d03cb6c26f59174956c238d88f4e) 👍

**Comment by soliwoli** [comment]
latest update doesnt fix this for some reason
