### ISSUE TITLE
extremely low fps

### ISSUE THREAD

**Issue by rayz132675** [NelloKudo/osu-winello#25]
use a laptop with a 3060 laptop gpu and a ryzen 7 5800h. used to get around 2000fps while playing, but after i reinstalled it, im barely getting 80fps on the main menu. also using linux mint and all my drivers are updated. any help would be great :D

**Comment by Sclafus** [comment]
Looks like a compositor issue tbf. I do not know if it can be speed-up on Cinnamon, but I'm pretty sure it can be speed-up on KDE/KWin.

**Comment by NelloKudo** [comment]
> use a laptop with a 3060 laptop gpu and a ryzen 7 5800h. used to get around 2000fps while playing, but after i reinstalled it, im barely getting 80fps on the main menu. also using linux mint and all my drivers are updated. any help would be great :D

First of all, check your drivers using this guide: https://github.com/lutris/docs/blob/master/InstallingDrivers.md

After those, does your pc happen to have an integrated igpu too? If so, make sure you’re running game on the dedicated one, Optimus Manager should work for that.

Last but not least, what @Sclafus mentioned: if you’re on Cinnamon, go to options > general and make sure “Disable compositing for fullscreen apps” is enabled.

**Comment by rayz132675** [comment]
> > First of all, check your drivers using this guide: https://github.com/lutris/docs/blob/master/InstallingDrivers.md
> 
> After those, does your pc happen to have an integrated igpu too? If so, make sure you’re running game on the dedicated one, Optimus Manager should work for that.
> 
> Last but not least, what @Sclafus mentioned: if you’re on Cinnamon, go to options > general and make sure “Disable compositing for fullscreen apps” is enabled.


Disabled compositing and made sure my drivers were updated, but none of them helped. Saw that optimus manager was only for arch based distros, so I tried running "__NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia osu-wine", but it still seemed to be running on the integrated igpu instead of my 3060. I also seemed to be getting around 60% cpu usage while i was tabbed into osu!.

**Comment by rayz132675** [comment]
Forget to mention this, but I'm using KDE Plasma.

**Comment by NelloKudo** [comment]
> > First of all, check your drivers using this guide: https://github.com/lutris/docs/blob/master/InstallingDrivers.md
> > After those, does your pc happen to have an integrated igpu too? If so, make sure you’re running game on the dedicated one, Optimus Manager should work for that.
> > Last but not least, what @Sclafus mentioned: if you’re on Cinnamon, go to options > general and make sure “Disable compositing for fullscreen apps” is enabled.
> 
> Disabled compositing and made sure my drivers were updated, but none of them helped. Saw that optimus manager was only for arch based distros, so I tried running "__NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia osu-wine", but it still seemed to be running on the integrated igpu instead of my 3060. I also seemed to be getting around 60% cpu usage while i was tabbed into osu!.

Please refer to [this](https://forums.linuxmint.com/viewtopic.php?p=2056347), that's probably what you're looking for Nvidia Prime to work properly on Mint.

**Comment by rayz132675** [comment]
> > > First of all, check your drivers using this guide: https://github.com/lutris/docs/blob/master/InstallingDrivers.md
> > > After those, does your pc happen to have an integrated igpu too? If so, make sure you’re running game on the dedicated one, Optimus Manager should work for that.
> > > Last but not least, what @Sclafus mentioned: if you’re on Cinnamon, go to options > general and make sure “Disable compositing for fullscreen apps” is enabled.
> > 
> > 
> > Disabled compositing and made sure my drivers were updated, but none of them helped. Saw that optimus manager was only for arch based distros, so I tried running "__NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia osu-wine", but it still seemed to be running on the integrated igpu instead of my 3060. I also seemed to be getting around 60% cpu usage while i was tabbed into osu!.
> 
> Please refer to [this](https://forums.linuxmint.com/viewtopic.php?p=2056347), that's probably what you're looking for Nvidia Prime to work properly on Mint.


turns out I was an idiot and all I had to do was switch from nvidia performance mode to on-demand mode and run osu! again💀
