### ISSUE TITLE
dependency issues not fixed for me

### ISSUE THREAD

**Issue by soliwoli** [NelloKudo/osu-winello#26]
latest update doesnt fix this for some reason

_Originally posted by @soliwoli in https://github.com/NelloKudo/osu-winello/issues/24#issuecomment-1461114445_

**Comment by NelloKudo** [comment]
could you please provide some logs or at least what isn’t working?

**Comment by soliwoli** [comment]
the same as before
_E: Package 'winetricks' has no installation candidate
E: Unable to locate package steam
Script failed: Some libraries didn't install for some reason, check apt or your connection
Reverting install...:
Reverting done, try again with ./osu-winello.sh_

**Comment by NelloKudo** [comment]
> the same as before
> _E: Package 'winetricks' has no installation candidate E: Unable to locate package steam Script failed: Some libraries didn't install for some reason, check apt or your connection Reverting install...: Reverting done, try again with ./osu-winello.sh_

Please make sure to git clone the script again, or run “git pull” in the repo. Winetricks isn’t even listed as dependency anymore (as it is not needed since my script installs a newer version)

**Comment by soliwoli** [comment]
ty again
