### ISSUE TITLE
alt tabbing causes osu to freeze, cant do anything unless you kill the process

### ISSUE THREAD

**Issue by soliwoli** [NelloKudo/osu-winello#28]
issue

**Comment by NelloKudo** [comment]
Could you link a clip of that happening? Also what DE and distro.

**Comment by soliwoli** [comment]
debian / chromeos

**Comment by soliwoli** [comment]
https://user-images.githubusercontent.com/122650721/224515704-5fde8a6a-790b-4536-bcc2-d0a0ce4b0648.mp4

**Comment by soliwoli** [comment]
as

**Comment by soliwoli** [comment]
?

**Comment by NelloKudo** [comment]
Yeah that does look strange but I don’t know whether I can test it myself since I don’t own a Chromebook :/ I guess I’ll see assp

**Comment by chicco-carone** [comment]
> Yeah that does look strange but I don’t know whether I can test it myself since I don’t own a Chromebook :/ I guess I’ll see assp

Maybe you can try testing it with chrome os flex in a wm (it has the Linux thing) or there was a way to install the full version from a recovery image

**Comment by Sclafus** [comment]
> Maybe you can try testing it with chrome os flex in a wm (it has the Linux thing) or there was a way to install the full version from a recovery image

Might be worth trying, but also please remember that this project is focused on Osu! on Linux, not on every esoteric OS in existence. Also the linux shell is not _really_ supported on ChromeOS either, since it's running in a container. It is a very customized distro with a Gentoo base, but that's where the similarities end.

Nevertheless, It looks like a "DE" issue to me. I would suggest trying to run the Android version of [Osu!Lazer](https://github.com/ppy/osu/releases). I think it may be a better option overall, but I'm not sure if it is officially supported.

**Comment by chicco-carone** [comment]
> > Maybe you can try testing it with chrome os flex in a wm (it has the Linux thing) or there was a way to install the full version from a recovery image
> 
> Might be worth trying, but also please remember that this project is focused on Osu! on Linux, not on every esoteric OS in existence. Also the linux shell is not _really_ supported on ChromeOS either, since it's running in a container. It is a very customized distro with a Gentoo base, but that's where the similarities end.
> 
> Nevertheless, It looks like a "DE" issue to me. I would suggest trying to run the Android version of [Osu!Lazer](https://github.com/ppy/osu/releases). I think it may be a better option overall, but I'm not sure if it is officially supported.

I think that on chrome os because it's something for education you can only install Android apps from the Google play and osu Lazer (for now) is only an apk.

**Comment by Sclafus** [comment]
> I think that on chrome os because it's something for education you can only install Android apps from the Google play and osu Lazer (for now) is only an apk.

You can sideload APKs on Chrome OS via `adb`.

**Comment by NelloKudo** [comment]
> > Yeah that does look strange but I don’t know whether I can test it myself since I don’t own a Chromebook :/ I guess I’ll see assp
> 
> Maybe you can try testing it with chrome os flex in a wm (it has the Linux thing) or there was a way to install the full version from a recovery image

I guess I'll give this a shot 👍

**Comment by NelloKudo** [comment]
https://user-images.githubusercontent.com/98063377/226118927-513c4f48-dec5-4a21-8cbd-dadb9ba763f8.mp4

Quick update: I got the game working out of alt-tab using Wine Staging 8.4, so a newer Wine probably does the job in fixing stuff.
I was planning to release a newer Wine anyways, so once I have it working that should work ootb.
(Oh anyways I don't have audio working for whatever reason)

**Comment by soliwoli** [comment]
huh, i updated to wine 8.4 staging

**Comment by NelloKudo** [comment]
_Took me a while but I now have a new Wine build lol_

![image](https://user-images.githubusercontent.com/98063377/231854960-1c60213e-99e0-421f-8889-6b68229a8215.png)

Replace the one you have with the following:

```bash
wget -O wine-osu-8.5-x86_64.tar.xz https://github.com/NelloKudo/WineBuilder/releases/download/wine-osu-tkg-8.5/wine-osu-8.5-x86_64.tar.xz
tar -xf wine-osu-8.5-x86_64.tar.xz
rm -rf ~/.local/share/osuconfig/wine-osu/
mv wine-osu ~/.local/share/osuconfig/ 
```

Closing as I have no clue of other ways to fix besides this. Worked on my machine so xd
