### ISSUE TITLE
Error during installation and very low fps

### ISSUE THREAD

**Issue by JGSphaela** [NelloKudo/osu-winello#29]
Hi, first of all I'm very appreciated about this project and would like to thank you for your hard work!

I recently install osu! using this script on a freshly installed Arch Linux with KDE Plasma.
During installation, I encountered an error "This application could not be started". Despite that, the installation was complete and osu! can startup with no problem. But, I get very low fps even just in the main menu(50fps~) and worse in editor(20fps~). I tried multiple method to fix the problem but no luck.

The error during installation:
![Screenshot_20230321_154651](https://user-images.githubusercontent.com/39881472/226537261-1de8d567-340b-44d8-b65e-665328c06531.png)

Ingame screenshot:
![Screenshot_20230321_160113](https://user-images.githubusercontent.com/39881472/226537636-d352e27c-6139-4250-a4e2-3ba87638bbce.png)

If I switch osu! to compatible mode, fps increase to my monitor refresh rate(165fps), but it won't go over that.

My setup(a desktop PC):
```
OS: Arch Linux x86_64
Kernel: 6.2.7-arch1-1
Packages: 978 (pacman)
Shell: fish 3.6.0
Resolution: 3840x2160
DE: Plasma 5.27.3
WM: kwin
Terminal: alacritty
CPU: AMD Ryzen 9 5950X (32) @ 3.400GHz
GPU: AMD Radeon RX 6900 XT
Memory: 8523MiB / 64222MiB
```

I checked my GPU driver:
```
~ [1]> sudo pacman -S --needed lib32-mesa vulkan-radeon lib32-vulkan-radeon vulkan-icd-loader lib32-vulkan-icd-loader
警告: lib32-mesa-22.3.6-1 は最新です -- スキップ
警告: vulkan-radeon-22.3.6-1 は最新です -- スキップ
警告: lib32-vulkan-radeon-22.3.6-1 は最新です -- スキップ
警告: vulkan-icd-loader-1.3.240-1 は最新です -- スキップ
警告: lib32-vulkan-icd-loader-1.3.240-1 は最新です -- スキップ
 何も行うことがありません
```
I also check my CPU and it clocked fine, with turbo enable and boosting to spec.
And I ran some benchmark to ensure both CPU and GPU performs just fine.
Running osu!lazer is also fine, albeit with much lower fps(only 400fps~) than running stable on Windows(maybe it's normal?).

I really want to get osu! working on Linux, any help would be really appreciated! Thanks in advance!

**Comment by NelloKudo** [comment]
> The error during installation: ![Screenshot_20230321_154651](https://user-images.githubusercontent.com/39881472/226537261-1de8d567-340b-44d8-b65e-665328c06531.png)
> 

Hello! You can actually ignore this error since it’s just related to dotnet45 being broken (lol) and it won’t affect the game in any way.

> Ingame screenshot: ![Screenshot_20230321_160113](https://user-images.githubusercontent.com/39881472/226537636-d352e27c-6139-4250-a4e2-3ba87638bbce.png)

Besides that, I think the issue here might be either Wayland or KWin’s fault.

If you happen to be on Wayland (you can check with `echo $XDG_SESSION_TYPE`), please refer to [this](https://osu.ppy.sh/community/forums/topics/1248084?n=263).

In any case, installing Autocomposer from Settings > KWin Scripts > Get from KDE Store should help as well.

Let me know if these work e.e

**Comment by JGSphaela** [comment]
Thank you so much!
Wayland is the issue! The [xorg-xwayland-osu](https://aur.archlinux.org/packages/xorg-xwayland-osu) package improved the most! follow by changing kernel, and using the autocomposer.
Huge thanks to Nello for helping me!!
