### ISSUE TITLE
Check if multilib was already enabled

### ISSUE THREAD

**Issue by hfleap** [NelloKudo/osu-winello#3]
I already had multilib enabled when I ran the script, and it added it again.
Maybe just checking if there is a line that starts with "[multilib]" in pacman.conf will do it.

**Comment by NelloKudo** [comment]
I actually forgot to change that when editing the script, damn it xD
Sorry about that, last update was so full of stuff I probably forgot to check that

I’ll fix asap 😅

**Comment by hfleap** [comment]
Made a quick pr to help with that 🤝
https://github.com/NelloKudo/osu-winello/pull/4
