### ISSUE TITLE
importing osu song folders doesnt show the maps in selection?

### ISSUE THREAD

**Issue by soliwoli** [NelloKudo/osu-winello#31]
it says i have 87 maps installed but when i check its only the tutorial maps

**Comment by chicco-carone** [comment]
> it says i have 87 maps installed but when i check its only the tutorial maps

Maybe you should try pressing F5 to reload the database?

**Comment by soliwoli** [comment]
im on chromebook whats the equivalent of that

**Comment by NelloKudo** [comment]
> im on chromebook whats the equivalent of that

I think you should probably look that up for yourself xd just try to set a shortcut for it

I also suggest looking at this: https://github.com/ppy/osu-wiki/blob/master/wiki/Client/Keyboard_shortcuts/en.md

**Comment by soliwoli** [comment]
f5 didnt work

**Comment by NelloKudo** [comment]
> f5 didnt work

are you sure maps refreshed properly? like did anything actually show up when you pressed f5 or were you stuck at song selection?

**Comment by soliwoli** [comment]
yep it just flashed for a second and nothing changed

**Comment by Sclafus** [comment]
From the game itself, do "Open osu! folder"
Check that the path where you are putting your maps is the same as the osu! one
F5 does not have an equivalent in Chromebooks
