### ISSUE TITLE
Gentoo improvement's

### ISSUE THREAD

**Issue by cronyakatsuki** [NelloKudo/osu-winello#32]
Hi, just tried to use your script today and have seen two things that need improvement's for your gentoo support.

1. Check if the `/etc/portage/package.use` is a file instead of a directory and if it is just append the line.
2. Enable 32bit support only on specific packages instead of the whole system, otherwise it makes almost the whole system to get a reinstallation, when only a few packages actually need 32bit support.

From what I remember just emerging a package like wine or wine staging on gentoo automatically add the 32bit flags to needed packages without having to reinstall the whole system with the global flag.

**Comment by NelloKudo** [comment]
I don't have a Gentoo install ready at the moment, looking into this asap 🙏🏻
