### ISSUE TITLE
Bass-Boosted sound

### ISSUE THREAD

**Issue by UsernameLoxotron** [NelloKudo/osu-winello#34]
I have a bass-boosted sound, don't look at fps, I have Intel Celeron and just want to try to run the game with good sound (If it's possible)
Video(Sorry, it doesn't record the sound)

https://github.com/NelloKudo/osu-winello/assets/68998003/fdaf0485-669a-47a6-b406-5284fd2b9d02

Also it says about audio driver card problem: 

![Screenshot 2023-05-27 2 03 48 PM](https://github.com/NelloKudo/osu-winello/assets/68998003/2c9b5e75-8119-4566-8836-ffe1bd86d89a)

**Comment by NelloKudo** [comment]
I might need more info on this: what distro are you using?
Also make sure you installed PipeWire the right way.

**Comment by UsernameLoxotron** [comment]
Chromebook? Idk what distro is this, working like Ubuntu

**Comment by NelloKudo** [comment]
Chromebooks’ performance won’t be that good since Linux is running in a sort of container there iirc; therefore the same might be happening for audio.

What’s the output of `pactl info` on your system?

**Comment by UsernameLoxotron** [comment]
![Screenshot 2023-06-07 9 12 25 PM](https://github.com/NelloKudo/osu-winello/assets/68998003/79082a2f-2196-4141-b7de-ade30db328a9)
```
Connection failure: Connection refused
pa_context_connect() failed: Connection refused
```

**Comment by UsernameLoxotron** [comment]
Also my version: 
![Screenshot 2023-06-07 9 16 28 PM](https://github.com/NelloKudo/osu-winello/assets/68998003/11d9ce6a-2649-4452-890b-e65350e7a083)
```
pactl 14.2
Compiled with libpulse 14.2.0
Linked with libpulse 14.2.0
```

**Comment by NelloKudo** [comment]
Kinda late but I ended up trying a Chromebook and installing PipeWire there is no different from  installing it in a virtual machine: latency pretty much depend on ChromeOS' drivers, and having no audio is probably related to that as well. 

I'd just use Wine from repos and call it a day as it wouldn't change that much, but in such cases I just recommend playing on Lazer xd

**Comment by UsernameLoxotron** [comment]
Yes, it is late, now I am playing Hotline Miami 😬
But thanks for really great work by taking chromebook. Just please, don't
say you bought it... Good luck

**Comment by dng-nguyn** [comment]
Happened to me as well, apparently it occurs when running with wine-osu. How do I fix this?

**Comment by UsernameLoxotron** [comment]
> Happened to me as well, apparently it occurs when running with wine-osu. How do I fix this?

Idk, but this happenes because of Chromebook audio drivers. If you want to play OSU so much, you can play online version from chrome. Good luck

**Comment by dng-nguyn** [comment]
Oh I forgot to say that i wasn't running on chromebook but rather a somewhat old pc.
The problem occurs when I try to run osu! from lutris with wine-osu which introduces bass boosted sound and the game at 0.5x speed, while other wine runners did not have the problem. It works fine from running osu-wine command though so probably some lutris settings messed it up.
