### ISSUE TITLE
Invalid argument during internet connection check

### ISSUE THREAD

**Issue by EllySensei** [NelloKudo/osu-winello#35]
OS: Arch Linux
`   Info "Checking for internet connection.."

    ! ping -c 1 1.1.1.1 >/dev/null 2>&1 && (! ping -c google.com && Error "Please connect to internet before continuing xd. Run the script again")`

There is no packet count on google.com, installation does continue.

**Comment by NelloKudo** [comment]
Fixed in latest commit, my bad there lmao 👍🏻
