### ISSUE TITLE
Osu crashing upon startup (arch)

### ISSUE THREAD

**Issue by whois-hoeless** [NelloKudo/osu-winello#37]
Hey, so once I start osu it crashes, I already tried reinstalling but that didn't work.. 
```
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  152 (GLX)
  Minor opcode of failed request:  3 (X_GLXCreateContext)
  Value in failed request:  0x0
  Serial number of failed request:  495
  Current serial number in output stream:  496
```
I am on arch with nvidia drivers. It all used to work fine but recently it just started crashing when I would start it.

**Comment by whois-hoeless** [comment]
I actually uninstalled wine, the script installs wine-8.10 (Staging) for me automatically

**Comment by NelloKudo** [comment]
Yep, the script does install Wine as a dependency but actually uses its own one, you can check the version with:

`~./local/share/osuconfig/wine-osu/bin/wine --version`

Even though tbf I don’t think it’s Wine’s fault here, can you write your hardware here?
Make sure your drivers are installed just fine as well.

**Comment by whois-hoeless** [comment]
Oh yeah the wine version is the correct one I assume: ```wine-8.9.1.r10.gd44a5161 ( TkG Staging Esync Fsync )```

OS: Arch Linux x86_64
Kernel: 6.3.8-arch1-1 
Nvidia Driver version: 535.54.03 (latest)
CPU: i7 11700k
GPU: RTX 3080 (proprietary drivers I am 99% sure)

Driver wise I don't think I changed or deleted something, I just update them when an update releases.
Also is there any specific driver I should have? I mean osu-wine used to work fine for me, I reinstalled it a few times all the packages are installed etc.

I think it's a problem with opengl but I don't know what it is specifically

**Comment by NelloKudo** [comment]
Please check if you have `lib32-nvidia-utils` installed, you can also refer to [this](https://github.com/lutris/docs/blob/master/InstallingDrivers.md).

Also give switching kernels a try, sometimes it magically does the job 🙏

Last try would be `osu-wine --fixprefix` but I don’t think prefix has anything to do with this xd

**Comment by NelloKudo** [comment]
Also did you install drivers using `nvidia-dkms` or just `nvidia`?

**Comment by Sclafus** [comment]
> Driver wise I don't think I changed or deleted something, I just update them when an update releases. 
Try reverting to a previous nvidia driver by reinstalling it via the pacman cache. It might not solve the problem, but worth a shot imho

**Comment by whois-hoeless** [comment]
> Please check if you have `lib32-nvidia-utils` installed, you can also refer to [this](https://github.com/lutris/docs/blob/master/InstallingDrivers.md).
> 
> Also give switching kernels a try, sometimes it magically does the job pray
> 
> Last try would be `osu-wine --fixprefix` but I don’t think prefix has anything to do with this xd

So actually --fixprefix did the job for me. To be fair, no clue what it did, it just did a whole lot of something and now everything seems to work again. Thank you for the answer :)
