### ISSUE TITLE
NixOS {question}

### ISSUE THREAD

**Issue by Demine0** [NelloKudo/osu-winello#38]
Do you plan to add support for the Nix OS?
Since configuration.nix installs packages and always installs them in /nix/store the script does not work, I think it would be easier to write nixpkgs and specify the required dependencies in it. I found wine-osu and osu-stable packages in the unofficial nix gaming repository but they did not work for me. I used your script to play osu on Arch Linux before.

Regards Demine

**Comment by Sclafus** [comment]
Hi @Demine0, the nature of NixOS is very interesting but very complicated for this kind of projects.
Definitely open for a PR, but quite complicated to implement. You would have to bundle together the version of wine and you shouldn't be able to update it without updating the whole package, which is kinda problematic. Upstream updates cannot be blocked, and we don't know when a version of wine-osu will simply stop to work, requiring an obligatory emergency update

**Comment by NelloKudo** [comment]
I still haven't looked much into NixOS myself, but if the community packages aren't working then my best bet would be installing osu! through Lutris and then downloading one of my Wine builds into it. 

Integrating projects like this in NixOS would be really complicated indeed xd

Closing this for the time being 👍🏻
