### ISSUE TITLE
Why not DXVK ?

### ISSUE THREAD

**Issue by Zyfarok** [NelloKudo/osu-winello#39]
`osu-wine --lutris` returns:

> In runner options, select 'wine-osu' as Wine version and disable DXVK/VKD3D.

The question is why are you advising to disable DXVK/VKD3D ?
Also why not enabling them by default when launching via the osu-wine script too ?

osu! uses OpenGL by default, and DirectX only if using "Compatibility mode".
Thus, enabling/disabling DXVK will not change anything unless you enable Compatibility mode, and as far as I can tell, on my setup performances in Compatibility mode are terrible without DXVK but actually quite good with DXVK. As far as I can remember from my past discussion and research, this is the same for most people.
I get similar performances with OpenGL than with Compatibility mode + DXVK, but it seems that I have less lag-spikes with DXVK and I remember seeing similar feedback on the osu! forum before, with more benefits for some than others, probably due to the variable levels of Vulkan and OpenGL support of the various linux gpu drivers.

Thus my question: Since having DXVK enabled has no drawbacks when running on OpenGL and can potentially deliver a smoother performances than OpenGL on some setups, why would you disable it ?

P.S.: Thank you for your great work. I remember the hassle of installing and tweaking everything to have osu! working with low latency in the past, and your script eases the installation a ton !

**Comment by NelloKudo** [comment]
The reason I advised to disable DXVK is because there were many reports some months ago about the game not launching on Lutris when using DXVK, with osu! complaining that "it wasn't able to find video drivers" or something like that xd

I have no clue whether it was a Lutris' runtime problem or an osu! related one, but in order to avoid stuff like that happening again I just decided to go the safest way. I'm gonna test whether DXVK actually has an impact on performance 🙏🏻

**Comment by Sclafus** [comment]
just tossing my 2 cents, but the game is waaaaay more laggy these days. It has microfreezes every 4-5 seconds, and major freezes every couple minutes. Hopefully dxvk can fix this

**Comment by Zyfarok** [comment]
> some months ago about the game not launching on Lutris when using DXVK

Oh indeed mybad, I missed that point and it seems to still be the case : I probably didn't launch the game with compatibility mode disabled and DXVK enabled yesterday, but when I tried just now, it didn't want to start, saying it was unable to obtain a graphic context. I guess it makes sense to not have DXVK by default then indeed but at least provide explanation on how people can try it if they want.

**Comment by Inconn** [comment]
i don't even think osu uses directx though? i think it only uses it on compatibility mode, right?

**Comment by Zyfarok** [comment]
> i think it only uses it on compatibility mode, right?

Yes that's correct and that's what I said above, and DXVK should only impact osu! In compatibility mode but it seems DXVK interferes when launching the game in OpenGL mode somehow anyway.

**Comment by ClickNinYT** [comment]
osu! using OpenGL instead of DirectX helps old non-Vulkan GPUs a lot. On my 2011 laptop even on Windows OpenGL outperforms DirectX even with Intel Integrated Graphic (anyone knows older Intel graphic drivers on Windows sucks).

**Comment by Sclafus** [comment]
@ClickNinYT FYI, OpenGL is not super supported by OS or driver developers anymore, it's 30+ years old.

**Comment by ClickNinYT** [comment]
Yeah I know, but its still worlds better than DirectX.
Though yeah Vulkan is the future, just OpenGL is still superior for older hardware that doesn't support Vulkan.

**Comment by NelloKudo** [comment]
Closing this as well, I did end up trying a prefix with DXVK and nothing really changed as expected. 
osu! crashing when it is enabled is probably related to Lutris anyways xd

**Comment by Zyfarok** [comment]
Yes, indeed as you said.
@NelloKudo Did you however at least consider changing the tuto, maybe including a note in the startup script too, and changing the message when using "osu-wine --lutris" so that people can know that they can try Vulkan if they want but it requires using compatibility mode as it will crash otherwise ?
