### ISSUE TITLE
PSA: Poor performance ~4.0ms on default installation

### ISSUE THREAD

**Issue by b1scoito** [NelloKudo/osu-winello#40]
By running

```bash
$ osu-wine --winecfg
```

And enabling the "Enable VAAPI as backend for DXVA2 GPU decoding" checkbox I now get 0.34ms and 1000 > FPS.

**Comment by Sclafus** [comment]
FYI, I did not encounter this issue.
What GPU are you using and with which driver?

**Comment by b1scoito** [comment]
> FYI, I did not encounter this issue. What GPU are you using and with which driver?

GTX 1060 6GB Driver Version 535.98
Running on Xorg with i3wm

**Comment by NelloKudo** [comment]
I think I've never heard of that setting affecting performance that much, on my setup (AMD) the game gives the same exact performance with or without it (~0.35ms). Looking into it as soon as I'm on an nvidia setup, I wonder if it's driver-related.

**Comment by Sclafus** [comment]
I am running with a very similar system (GTX 1070, 535.98, Linux 6.4.10) on Plasma 5+Xorg, and I don't see any improvement with the option on/off either
Have you tried without i3wm? 4.0ms sounds like a frame rate cap to me.

**Comment by NelloKudo** [comment]
Turns out that DXVA2 has actually been disabled for a while in Wine, so unless you’re using a pretty old Staging build (which is not the case with this script) any difference should be placebo. 

I guess in your case it was just prefix doing its things/drivers not updated correctly (?) I’m pretty sure disabling that now in winecfg should give you the same exact performance.

**Comment by b1scoito** [comment]
I'm running Arch Linux with everything on latest. Will test without to see if I it changes FPS once again. I found it weird since on a fresh install I'd get 4.0ms so I started messing around with configs and randomly I enabled that option and I started to get 0.30ms which is so weird to me.

**Comment by b1scoito** [comment]
Just tested. After disabling that option. performance is still great. Probably something related to the first run or the first runs of Wine.

**Comment by NelloKudo** [comment]
Closing as this sounds fixed 👍🏻
