### ISSUE TITLE
discord 

### ISSUE THREAD

**Issue by AnimeWaifuGirl** [NelloKudo/osu-winello#42]
discord rich presence doesn't work for me after i installed osu!stable over you're osu-winello script!
what im need to do to fix that issue

**Comment by NelloKudo** [comment]
I need some info first:

1. What is your distro?
2. How did you install discord?

If you're using Flatpak Discord, then please refer to [this](https://github.com/flathub/com.discordapp.Discord/wiki/Rich-Precense-(discord-rpc)).

**Comment by AnimeWaifuGirl** [comment]
Sure I installed Discord, my distro is Arch Linux with no pre-installed environment, I installed Fluxbox afterwards

**Comment by NelloKudo** [comment]
You simply installed it from pacman? It should be working then. 
If rebooting or checking Discord settings is not working, run `osu-wine --fixprefix`

**Comment by AnimeWaifuGirl** [comment]
it dosent work but i found a exe in this prefix
/.local/share/wineprefixes/osu-wineprefix/drive_c/winestreamproxy/ what do this exe in thats folder, called winestramproxy.exe

**Comment by AnimeWaifuGirl** [comment]
I have no idea why this is working right now I was looking for help but it has always been this way with me!

but thanks for the quick answers

**Comment by NelloKudo** [comment]
That's the exe providing RPC after it's installed inside the prefix, so as long as it's there it should be working if your system is 64-bit.
I guess you can try [this other option](https://github.com/0e4ef622/wine-discord-ipc-bridge):

- Download the .exe from releases and save it whenever
- Edit ~/.local/bin/osu-wine using something like nano: `nano ~/.local/bin/osu-wine`
- In line 67 (osu! launcher), replace `wine "$OSUPATH/osu!.exe"` with `wine /path/to/winediscordipcbridge.exe && wine "$OSUPATH/osu!.exe"`.

If none of these work, I guess it's something with your system xd
