### ISSUE TITLE
osu-winello.sh | W10Fonts invalid variable

### ISSUE THREAD

**Issue by JustRoxy** [NelloKudo/osu-winello#44]
https://github.com/NelloKudo/osu-winello/blob/main/osu-winello.sh#L998-L1001
```sh
    if [ "$fontsch" = 1 ] || [ "$fontsch" = 2 ] ; then  
    case "$installpath" in


    '1')
```

`$installpath` is not defined in the scope, causing function to exit with no logic executed on valid inputs.

**Comment by NelloKudo** [comment]
Oh you’re actually right on this lmao, I probably just copied the case function from `ConfigurePath` when I rewrote the script and ended up not changing `$installpath` with `$fontsch`. Gonna fix that in next commit, thanks for noticing!! 😭
