### ISSUE TITLE
Wacom table issues in Hyprland

### ISSUE THREAD

**Issue by tinytempmouse** [NelloKudo/osu-winello#46]
Hi I've tried using the Wayland tutorial you provided however the issue remains that I can tap to click but the cursor won't move at all. However everything works fine outside Osu wine.

**Comment by tinytempmouse** [comment]
I'm running Arch Linux with Hyprland

**Comment by NelloKudo** [comment]
I have to yet try Hyprland myself but all I know is that tablets aren’t officially supported there. I’ll give some more info once I get my hands on it 🙏

**Comment by AtelierMizumi** [comment]
@tinytempmouse I assume you're using OpenTabletDriver. Have you tried Artist Mode ?   

add this to /etc/libinput/local-overrides.quirks to disable smoothing
```
[OpenTabletDriver Virtual Tablets]
MatchName=OpenTabletDriver*
AttrTabletSmoothing=0
```

[#2075](https://github.com/OpenTabletDriver/OpenTabletDriver/issues/2075)
[disable artist mode smoothing related issue](https://github.com/OpenTabletDriver/OpenTabletDriver/issues/2895)
