### ISSUE TITLE
patched xwayland is outdated for fedora 39

### ISSUE THREAD

**Issue by nekoraw** [NelloKudo/osu-winello#47]
idk where to report this but the available version on suse's obs is outdated and i cant use it because packages on my system require a newer version

**Comment by Sclafus** [comment]
Hello 👋
To my knowledge, we are not publishing this project anywhere, it's only a script.
Can you please paste the link of what you found?

**Comment by nekoraw** [comment]
yeah i know you arent responsible for the xwayland fix but the link in the wiki points to an old version of it:

https://github.com/NelloKudo/osu-winello/wiki/Wayland-support (its the fedora link)

i will try to contact hwsnemo to update the package to the new fedora version
