### ISSUE TITLE
osu doesn't open after changing osu! directory

### ISSUE THREAD

**Issue by oaroki-git** [NelloKudo/osu-winello#49]
running on PopOS x11 gnome

it worked fine after default installation, but after running osu-wine --changedir and selecting /media/akira/Data/osu!, the osu! logo appears but dissapears and the program stops

terminal output:
`0598:err:system:NtUserChangeDisplaySettings Changing L"\\\\.\\DISPLAY1" display settings returned -2.
0598:err:explorer:initialize_display_settings Failed to initialize registry display settings for L"\\\\.\\DISPLAY1".
0410:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
0410:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 10003241, 28) stub
0410:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 011009AD, 28) stub
0410:fixme:heap:GetNumaHighestNodeNumber semi-stub: 0094FC74
0410:fixme:seh:WerRegisterRuntimeExceptionModule (L"C:\\windows\\Microsoft.NET\\Framework\\v4.0.30319\\mscordacwks.dll", 010F0000) stub
05b0:err:ole:CoGetContextToken apartment not initialised
0410:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 01D2A258, 65) stub
0410:fixme:nls:get_dummy_preferred_ui_language (0x8 0x409 0094DCC0 00000000 0094DCC4) returning a dummy value (current locale)
0410:fixme:nls:get_dummy_preferred_ui_language (0x8 0x409 0094DCC0 00EB6F48 0094DCC4) returning a dummy value (current locale)
0410:fixme:cryptasn:CryptDecodeObjectEx Unsupported decoder for lpszStructType 1.3.6.1.4.1.311.2.1.4
0410:fixme:cryptasn:CryptDecodeObjectEx Unsupported decoder for lpszStructType 1.3.6.1.4.1.311.2.1.4
0410:fixme:ntdll:NtQuerySystemInformation (0x000000ce,0x94d42c,0x00000008,(nil)) stub
0410:fixme:bcrypt:BCryptGetFipsAlgorithmMode 0094DEBC - semi-stub
0410:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 01D8F240, 51) stub
0410:fixme:wldp:WldpIsDynamicCodePolicyEnabled 0094E648
0410:fixme:amsi:AmsiInitialize L"DotNet", 0094E638
0410:fixme:amsi:AmsiScanBuffer DEADBEEF, 02D314E0, 223232, (null), 00000000, 0094E62C
069c:fixme:combase:RoGetParameterizedTypeInstanceIID stub: 4 07B952F8 07B2B7F8 07B2BE40 00000000
069c:fixme:combase:RoGetParameterizedTypeInstanceIID stub: 3 07BAA8A4 07B2B9E8 07B2C030 00000000
069c:fixme:combase:RoGetParameterizedTypeInstanceIID stub: 3 07BAA8A4 07B2B9E8 07B2C030 00000000
0410:fixme:process:SetProcessPriorityBoost (00000320,0): stub
05f0:fixme:ras:RasEnumConnectionsW (07C7C660,0ADEEEA4,0ADEEEA8),stub!
05f0:fixme:ras:RasEnumConnectionsW RAS support is not implemented! Configure program to use LAN connection/winsock instead!
0410:fixme:ntdll:NtQuerySystemInformation SystemCodeIntegrityInformation, size 8, info 0x94edb8, stub!
0204:fixme:dciman:DCICreatePrimary 0101004E 0A0515FC
05f0:fixme:ras:RasConnectionNotificationW (FFFFFFFF,00000364,0x00000003),stub!
05f0:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 01DC4BB4, 53) stub
0550:fixme:amsi:AmsiScanBuffer DEADBEEF, 02DAC830, 180736, (null), 00000000, 0BE3EDA8
05f0:err:winediag:ntlm_check_version ntlm_auth was not found. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
05f0:err:ntlm:ntlm_LsaApInitializePackage no NTLM support, expect problems
05f0:fixme:ver:GetCurrentPackageId (0ADEEAD0 00000000): stub
05ec:fixme:kernelbase:AppPolicyGetThreadInitializationType FFFFFFFA, 0DA1FEF8
05f0:fixme:secur32:get_cipher_algid unknown algorithm 23
05f0:fixme:secur32:get_mac_algid unknown algorithm 200, cipher 23
05f0:fixme:secur32:get_cipher_algid unknown algorithm 23
05f0:fixme:secur32:get_mac_algid unknown algorithm 200, cipher 23
05f0:fixme:crypt:CertAddCertificateLinkToStore (00E3EC70, 00E3D8BC, 00000004, 00000000): semi-stub
05f0:fixme:nls:GetFileMUIPath stub: 0x10, L"C:\\windows\\system32\\tzres.dll", (null), 0ADEE2A0, 07C2E770, 0ADEE2A4, 0ADEE298
05f0:fixme:nls:GetFileMUIPath stub: 0x10, L"C:\\windows\\system32\\tzres.dll", (null), 0ADEE2A0, 07C2E770, 0ADEE2A4, 0ADEE298
05f0:fixme:nls:GetFileMUIPath stub: 0x10, L"C:\\windows\\system32\\tzres.dll", (null), 0ADEE2A0, 07C2E770, 0ADEE2A4, 0ADEE298
0724:fixme:avrt:AvSetMmThreadCharacteristicsW (L"Audio",0F83FF10): stub
0550:fixme:cryptasn:CryptDecodeObjectEx Unsupported decoder for lpszStructType 1.3.6.1.4.1.311.2.1.4
0550:fixme:cryptasn:CryptDecodeObjectEx Unsupported decoder for lpszStructType 1.3.6.1.4.1.311.2.1.4
0410:err:wgl:glxdrv_wglShareLists Could not share display lists because both of the contexts have already been current or shared
0410:err:wgl:glxdrv_wglShareLists Could not share display lists because both of the contexts have already been current or shared
0410:err:wgl:glxdrv_wglShareLists Could not share display lists because both of the contexts have already been current or shared
0410:err:wgl:glxdrv_wglShareLists Could not share display lists because both of the contexts have already been current or shared
0410:err:wgl:glxdrv_wglShareLists Could not share display lists because both of the contexts have already been current or shared
0410:err:wgl:glxdrv_wglShareLists Could not share display lists because both of the contexts have already been current or shared
0484:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 02261CE4, 46) stub
05b0:fixme:ole:thread_context_callback_ContextCallback 0643177C, 012B81F0, 040BF798, {d7174f82-36b8-4aa8-800a-e963ab2dfab9}, 2, 00000000
05b0:fixme:ole:thread_context_callback_ContextCallback 0643177C, 012B81F0, 040BF71C, {d7174f82-36b8-4aa8-800a-e963ab2dfab9}, 2, 00000000
05b0:fixme:ole:thread_context_callback_ContextCallback 0643177C, 012B81F0, 040BF71C, {d7174f82-36b8-4aa8-800a-e963ab2dfab9}, 2, 00000000
`

**Comment by NelloKudo** [comment]
have you tried running `osu-wine --fixprefix`?

**Comment by oaroki-git** [comment]
Exits after output

`fsync: up and running.
002c:fixme:winediag:LdrInitializeThunk Wine TkG (staging) 8.16 is a testing version containing experimental patches.
002c:fixme:winediag:LdrInitializeThunk Please don't report bugs about it on winehq.org and use https://github.com/Frogging-Family/wine-tkg-git/issues instead.
002c:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -a -r" (2).
00b0:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
00b0:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
00b0:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
00b0:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
00f8:err:system:NtUserChangeDisplaySettings Changing L"\\\\.\\DISPLAY1" display settings returned -2.
00f8:err:explorer:initialize_display_settings Failed to initialize registry display settings for L"\\\\.\\DISPLAY1".
013c:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
0144:err:ole:CoGetContextToken apartment not initialised
013c:fixme:ntdll:EtwRegisterTraceGuidsW   register trace class {35167f8e-49b2-4b96-ab86-435b59336b5e}
013c:fixme:nls:get_dummy_preferred_ui_language (0x0 0x409 0094D060 00000000 0094D05C) returning a dummy value (current locale)
013c:fixme:nls:get_dummy_preferred_ui_language (0x0 0x409 0094D060 00EB5B88 0094D05C) returning a dummy value (current locale)
013c:fixme:cryptasn:CryptDecodeObjectEx Unsupported decoder for lpszStructType 1.3.6.1.4.1.311.2.1.4
013c:fixme:cryptasn:CryptDecodeObjectEx Unsupported decoder for lpszStructType 1.3.6.1.4.1.311.2.1.4
013c:fixme:ntdll:EtwRegisterTraceGuidsW   register trace class {8e9f5090-2d75-4d03-8a81-e5afbf85daf1}
013c:fixme:process:SetProcessPriorityBoost (00000368,0): stub
013c:fixme:ntdll:NtQuerySystemInformation SystemCodeIntegrityInformation, size 8, info 0x94e864, stub!
0178:fixme:crypt:SystemFunction041 (078A8124, 10, 0): stub [RtlDecryptMemory]
0178:fixme:ras:RasEnumConnectionsW (0792BE30,0907ED5C,0907ED60),stub!
0178:fixme:ras:RasEnumConnectionsW RAS support is not implemented! Configure program to use LAN connection/winsock instead!
0178:fixme:ras:RasConnectionNotificationW (FFFFFFFF,000003EC,0x00000003),stub!
0174:fixme:font:find_matching_face Untranslated charset 255
0174:fixme:font:get_nearest_charset returning DEFAULT_CHARSET face->fs.fsCsb[0] = 00000000 file = L"\\??\\Z:\\usr\\share\\fonts\\truetype\\noto\\NotoKufiArabic-Regular.ttf"
0174:fixme:gdiplus:GdipGetFamilyName No support for handling of multiple languages!
0174:fixme:gdiplus:GdipCreateHalftonePalette stub
0178:err:winediag:ntlm_check_version ntlm_auth was not found. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
0178:err:ntlm:ntlm_LsaApInitializePackage no NTLM support, expect problems
0194:fixme:kernelbase:AppPolicyGetThreadInitializationType FFFFFFFA, 0A91FEF8
0178:fixme:crypt:CertAddCertificateLinkToStore (05450128, 00E3D7FC, 00000004, 00000000): semi-stub
0178:fixme:nls:GetFileMUIPath stub: 0x10, L"C:\\windows\\system32\\tzres.dll", (null), 0907E154, 078A8758, 0907E158, 0907E14C
0178:fixme:nls:GetFileMUIPath stub: 0x10, L"C:\\windows\\system32\\tzres.dll", (null), 0907E154, 078A8758, 0907E158, 0907E14C
0178:fixme:nls:GetFileMUIPath stub: 0x10, L"C:\\windows\\system32\\tzres.dll", (null), 0907E154, 078A8758, 0907E158, 0907E14C
01a0:fixme:avrt:AvSetMmThreadCharacteristicsW (L"Audio",0F35FF10): stub
018c:fixme:cryptasn:CryptDecodeObjectEx Unsupported decoder for lpszStructType 1.3.6.1.4.1.311.2.1.4
018c:fixme:cryptasn:CryptDecodeObjectEx Unsupported decoder for lpszStructType 1.3.6.1.4.1.311.2.1.4
013c:err:wgl:glxdrv_wglShareLists Could not share display lists because both of the contexts have already been current or shared
013c:err:wgl:glxdrv_wglShareLists Could not share display lists because both of the contexts have already been current or shared
013c:err:wgl:glxdrv_wglShareLists Could not share display lists because both of the contexts have already been current or shared
013c:err:wgl:glxdrv_wglShareLists Could not share display lists because both of the contexts have already been current or shared
013c:err:wgl:glxdrv_wglShareLists Could not share display lists because both of the contexts have already been current or shared
013c:err:wgl:glxdrv_wglShareLists Could not share display lists because both of the contexts have already been current or shared
`

**Comment by oaroki-git** [comment]
maybe something with the fonts? it might fix itself after running `--fixprefix` a couple more times

**Comment by oaroki-git** [comment]
it starts up after changing back to the default install path in ~/.local/...

FYI i replied "no" on all occasions when asked if i wanted to delete previous install

**Comment by NelloKudo** [comment]
Then the one at fault here is probably your hard drive or how it’s mounted. Have you already created an entry for it in fstab? If so what options are you using to mount it?

If you haven’t added it yet, then refer to [this](https://github.com/ValveSoftware/Proton/wiki/Using-a-NTFS-disk-with-Linux-and-Windows).

**Comment by oaroki-git** [comment]
After following the steps and changing the directory back, it exits with

`fsync: up and running.
002c:fixme:winediag:LdrInitializeThunk Wine TkG (staging) 8.16 is a testing version containing experimental patches.
002c:fixme:winediag:LdrInitializeThunk Please don't report bugs about it on winehq.org and use https://github.com/Frogging-Family/wine-tkg-git/issues instead.
002c:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -a -r" (2).
00b0:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
00b0:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
00b0:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
00b0:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
00f8:err:system:NtUserChangeDisplaySettings Changing L"\\\\.\\DISPLAY1" display settings returned -2.
00f8:err:explorer:initialize_display_settings Failed to initialize registry display settings for L"\\\\.\\DISPLAY1".
013c:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
0144:err:ole:CoGetContextToken apartment not initialised
013c:fixme:ntdll:EtwRegisterTraceGuidsW   register trace class {35167f8e-49b2-4b96-ab86-435b59336b5e}
013c:fixme:nls:get_dummy_preferred_ui_language (0x0 0x409 0094D060 00000000 0094D05C) returning a dummy value (current locale)
013c:fixme:nls:get_dummy_preferred_ui_language (0x0 0x409 0094D060 00EC7FF8 0094D05C) returning a dummy value (current locale)
013c:fixme:cryptasn:CryptDecodeObjectEx Unsupported decoder for lpszStructType 1.3.6.1.4.1.311.2.1.4
013c:fixme:cryptasn:CryptDecodeObjectEx Unsupported decoder for lpszStructType 1.3.6.1.4.1.311.2.1.4
013c:fixme:ntdll:EtwRegisterTraceGuidsW   register trace class {8e9f5090-2d75-4d03-8a81-e5afbf85daf1}
013c:fixme:process:SetProcessPriorityBoost (00000368,0): stub
013c:fixme:ntdll:NtQuerySystemInformation SystemCodeIntegrityInformation, size 8, info 0x94e864, stub!
0178:fixme:crypt:SystemFunction041 (078A454C, 10, 0): stub [RtlDecryptMemory]
0178:fixme:ras:RasEnumConnectionsW (0793B3A8,08CAED5C,08CAED60),stub!
0178:fixme:ras:RasEnumConnectionsW RAS support is not implemented! Configure program to use LAN connection/winsock instead!
0178:fixme:ras:RasConnectionNotificationW (FFFFFFFF,00000454,0x00000003),stub!
0174:fixme:font:find_matching_face Untranslated charset 255
0174:fixme:font:get_nearest_charset returning DEFAULT_CHARSET face->fs.fsCsb[0] = 00000000 file = L"\\??\\Z:\\usr\\share\\fonts\\truetype\\noto\\NotoKufiArabic-Regular.ttf"
0174:fixme:gdiplus:GdipGetFamilyName No support for handling of multiple languages!
0174:fixme:gdiplus:GdipCreateHalftonePalette stub
`

my /etc/fstab:
`UUID=3228C99428C9580D /media/data ntfs uid=1000,gid=1000,rw,user,exec,umask=000 0 0`

**Comment by oaroki-git** [comment]
running osu-wine --fixprefix and then running osu-wine again seems to return the same error as the original comment

**Comment by NelloKudo** [comment]
Closing this for the time being, let me know if you know more or just hit me on discord (marshnello) o/
