### ISSUE TITLE
Script detect as Arch when wine detected on Debian

### ISSUE THREAD

**Issue by ragasubekti** [NelloKudo/osu-winello#50]
As the title suggested the script tries to run pacman when wine is detected, the previous stage of the installation script still run using apt

![image](https://github.com/NelloKudo/osu-winello/assets/20393246/97904ccc-9039-439a-ab60-9542f664f5e0)

**Comment by NelloKudo** [comment]
Really strange issue, I have no idea why pacman’d be detected on Debian or why it is even a command xd. Quickest fix would be running `./osu-winello.sh --nodeps` since dependencies have been already installed for your system, but I’ll push an update later to fix. Let me know if nodeps worked tho hehe

**Comment by ragasubekti** [comment]
Seems like the issues comes from my shell, replacing it with bash/zsh the script working as intended. Also it seems the repository still use bullseye repository, possible to change to the latest one (bookworm) or pull the version from `lsb_release -c`?

**Comment by NelloKudo** [comment]
Glad it fixed :D

Also I'm no Debian expert soo I have no idea what `lsb_release` would do, I've wanted to improve how the script adds the repo as well for a while but I don't have much clues about it xd
I guess I'll see what I can do!

**Comment by ragasubekti** [comment]
no worries it should also work on ubuntu, lsb_release usually come preinstalled on debian/ubuntu based distro so it will look like this when `lsb_release -c` is run:

```bash
noir@debian:~$ lsb_release -c
No LSB modules are available.
Codename:       bookworm
```

**Comment by NelloKudo** [comment]
Thanks for the info!! I’ll make sure to implement it then. Closing the issue once I get the job done 🙏
