### ISSUE TITLE
Gamma control?

### ISSUE THREAD

**Issue by Roroca-1** [NelloKudo/osu-winello#51]
Is there any possible way to add gamma control to better play with low/high ar?

**Comment by Sclafus** [comment]
Isn't this delegated to the DE or the compositor already? I can change it from the KDE settings and it applies to the game.

**Comment by Roroca-1** [comment]
is there a way to change with gnome+wayland? all the posts i can find are from 2012 🥵

**Comment by NelloKudo** [comment]
I can't implement it in the script myself, but there is [this project](https://github.com/zb3/gnome-gamma-tool) which works quite well.
You can pretty much download it with:
```
git clone https://github.com/zb3/gnome-gamma-tool
cd gnome-gamma-tool
./gnome-gamma-tool.py -d X -g R:G:B
```
...where **X is the number of your monitor** and **R:G:B the values** you want to apply. You can pretty much take them from Windows I guess?

So an example would be: `./gnome-gamma-tool.py -d 1 -g 3:3:3`

Sucks that you need to use terminal, but it is what it is xD
Closing this, hit me on discord (marshnello) if you need more help o/
And to go back to default settings: `./gnome-gamma-tool.py -d 1 -g 1:1:1`

If you want a single command to launch it after cloning, just use `./gnome-gamma-tool/gnome-gamma-tool.py -d 1 -g 3:3:3`
