### ISSUE TITLE
using OBS destroys fps

### ISSUE THREAD

**Issue by Roroca-1** [NelloKudo/osu-winello#52]
using GNOME on Wayland, flatpak obs
Display Capture doesn't capture osu window (froze)
Window Capture captures osu window but experience stutters, input lag and fps drop in osu

**Comment by NelloKudo** [comment]
I need quite more info to actually help you xd
What's your pc config? And what distro are you using?

**Comment by Roroca-1** [comment]
i'm using Nobara37 with 12600KF and RTX3070

**Comment by Roroca-1** [comment]
switched to kde, fixed everything
