### ISSUE TITLE
After updating to 8.21, osu! window always launches in the top left corner of the screen

### ISSUE THREAD

**Issue by PhoenixEmik** [NelloKudo/osu-winello#53]
As the title suggests. Recent osu! stable update broke custom fullscreen resolution while alt-tabbing... So I decided to play with windowed mode.
Reverting to 8.16 everything goes ok. 
Environment: KDE, X11

**Comment by NelloKudo** [comment]
That is because latest stable update broke alt-tab on Wine in general and 8.21 was patched to force the game to always go on the top-left of the screen to workaround it for Fullscreen at least.

8.16 has such problems on all other DEs so I needed to push a fix for it, but reverting to it sounds totally fine too. While we wait for a fix, use 8.16 ;)

**Comment by NelloKudo** [comment]
Quick test with 8.21 on KDE X11, latest stable update
osu! in fullscreen mode seems to work flawlessly even with custom resolutions, it only breaks
with windowed as mentioned earlier. Maybe you could try resetting your osu! config?

https://github.com/NelloKudo/osu-winello/assets/98063377/cc4c3536-5af5-4e9c-9328-20a9de791226

**Comment by PhoenixEmik** [comment]
I set fullscreen resolution manually in my osu! config file by editing these two values: 
```ini
HeightFullscreen = 990
WidthFullscreen = 1760
```
After alt-tabbing, the values will always be restored to 1080 & 1920. Not sure if this issue is related to wine or osu! itself.

**Comment by NelloKudo** [comment]
Even though the custom fullscreen resolution thing still doesn't work on KDE, this [9.0-rc1 release](https://github.com/NelloKudo/WineBuilder/releases/tag/wine-osu-tkg-9.0-rc1) has a `no-resetpos-patch` version which should work great if you want to play in Windowed mode. 

Please let me know if it works well! I'll probably add this to the Wiki as well, at least until the resetpos patch won't be needed anymore.

**Comment by PhoenixEmik** [comment]
The custom fullscreen resolution got broken after osu! stable 20231121.5 update, so 8.16 doesn't work well (on KDE) either.
I'll look into no-patch 9.0-rc1 version later.

**Comment by NelloKudo** [comment]
Did a little bit of testing and yeah that still happens on 9.0-rc1, but works ootb on Wine-GE.
Proton probably has some winex11drv patch changing that behavior I guess xd

Here's the build with osu! patches if you wanna try it out, closing the issue for the time being. 🥳  https://github.com/NelloKudo/WineBuilder/releases/tag/wine-ge-8-25-osu

**Comment by PhoenixEmik** [comment]
Wine-GE works fine and solves the fullscreen custom resolution issue. Thanks!
It would be good to add an option that uses wine-ge instead of the mainstream version. I'd like to PR later.
