### ISSUE TITLE
 New wine osu version focus issues

### ISSUE THREAD

**Issue by cronyakatsuki** [NelloKudo/osu-winello#56]
The new wine osu version has issues with focusing the window, making it so I need to reboot the system for it to function properly again.

Border just keeps flickering and locks me to one workspace ( I use xmonad ) and also leaves a phantom window that keeps my system focused on it only.

Also happens when I run osu-wine --winecfg, the winecfg border keeps flickers and locks my sytem.

**Comment by NelloKudo** [comment]
What version were you using before updating? 8.21?

**Comment by cronyakatsuki** [comment]
I  didn't play osu for a couple months so It was prob more like wine 7, or an older 8 version.

**Comment by cronyakatsuki** [comment]
I have  went ahead and downgraded  my wine version to 8.20 manually and the issue doesn't exist there. The issue must have been introduced with 8.21

**Comment by NelloKudo** [comment]
Oh I see now, yeah the latest Wine versions have a workaround patch to fix alt-tab after the latest stable update, which forces osu! to go on the top left of the screen regardless when focused. It probably doesn't work properly on XMonad I guess xd

Indeed just today I also built a version of 9.0 without that patch, install it with the following and tell me if anything changes :pray:

```
rm -rf ~/.local/share/osuconfig/wine-osu
wget -O wine-osu-tkg-9.0-rc1-x86_64.tar.xz https://github.com/NelloKudo/WineBuilder/releases/download/wine-osu-tkg-9.0-rc1/wine-osu-tkg-9.0-rc1-no-resetpos-patch-x86_64.tar.xz
tar -xf wine-osu-tkg-9.0-rc1-x86_64.tar.xz
mv wine-osu ~/.local/share/osuconfig
```

**Comment by cronyakatsuki** [comment]
> Oh I see now, yeah the latest Wine versions have a workaround patch to fix alt-tab after the latest stable update, which forces osu! to go on the top left of the screen regardless when focused. It probably doesn't work properly on XMonad I guess xd
> 
> Indeed just today I also built a version of 9.0 without that patch, install it with the following and tell me if anything changes 🙏
> 
> ```
> rm -rf ~/.local/share/osuconfig/wine-osu
> wget -O wine-osu-tkg-9.0-rc1-x86_64.tar.xz https://github.com/NelloKudo/WineBuilder/releases/download/wine-osu-tkg-9.0-rc1/wine-osu-tkg-9.0-rc1-no-resetpos-patch-x86_64.tar.xz
> tar -xf wine-osu-tkg-9.0-rc1-x86_64.tar.xz
> mv wine-osu ~/.local/share/osuconfig
> ```

With the wine version you just provided it now works without any issues!

**Comment by NelloKudo** [comment]
Wonderful! Thanks for testing, I guess we'll have to live with the two different versions until a better fix is found. 
Might also create a command to just switch between the two xd
