### ISSUE TITLE
Stuck On 60fps

### ISSUE THREAD

**Issue by FierraCodes** [NelloKudo/osu-winello#59]
Osu is stuck on 60fps ever since i changed to a **low latency kernel (linux-image-5.15.0-91-lowlatency).** It was running fine on the normal kernel (linux-image-6.0.2-generic), so why can't it run as good as the normal kernel? The reason why I switched to the lowlatency kernel is because it literally doubled my fps on any other games like Minecraft, McOsu and any other. I've reinstalled osu-wine completely and nothing has changed. Please help.

**Comment by NelloKudo** [comment]
Can I have some more info on your system? Like what's your desktop environment, how you installed drivers, if you're on X11/Wayland etc.

**Comment by FierraCodes** [comment]
x11, drivers are either 5.25 or 5.35 with the additional driver installer in Ubuntu.

**Comment by NelloKudo** [comment]
Make sure you also install headers for the new kernel, idk the exact package name but drivers might be failing to install with dkms because of that.

**Comment by FierraCodes** [comment]
ah, that might be the problem. I'll try once I'm free since i reinstalled ubuntu.

**Comment by FierraCodes** [comment]
Yup, works like a charm, Thanks!
