### ISSUE TITLE
when installing osu!, it show that

### ISSUE THREAD

**Issue by deridray** [NelloKudo/osu-winello#60]
![image](https://github.com/NelloKudo/osu-winello/assets/97302909/ef056174-366b-43d4-b01b-748bb77111c0)
p.s: i have pop! os on kde plasma if it's important

**Comment by NelloKudo** [comment]
wait wtf 💀 try updating git I guess? or restart your pc

**Comment by deridray** [comment]
doesn't help

**Comment by NelloKudo** [comment]
`git clone https://github.com/YourRandomGuy/ttf-ms-win10.git` 

What if you run this yourself in a terminal? Does it work?
