### ISSUE TITLE
Build Wine 9 with wayland support

### ISSUE THREAD

**Issue by Kodehawa** [NelloKudo/osu-winello#61]
Using the regedit method to enable wayland on Wine 9 does not work. Could you build it with the option `--with-wayland`, please?

**Comment by NelloKudo** [comment]
I guess I could try, not sure how well the game’s gonna run under Wayland tho. Making a build for you later, if that works I guess I’ll update the script as well once 9.0 drops.

**Comment by NelloKudo** [comment]
https://www.dropbox.com/scl/fi/kk4tmo80inos0amjyuyue/wine-osu-tkg-9.0-rc3-x86_64.tar.xz?rlkey=bd73pv68j2tu663uddred8a5y&dl=0

Here it is, 9.0-rc3 + staging and tkg patches with wayland enabled. Let me know if it works or if you need help to set it up 🙏🏻

**Comment by NelloKudo** [comment]
https://www.dropbox.com/scl/fi/kk0sn6y6s2r99yxc90r71/wine-osu-tkg-9.0-rc3-x86_64.tar.xz?rlkey=wq7cf2amf3fs3sbe5ib92c3sz&dl=0

Here's 9.0-rc3 with Staging and TKG patches + Wayland enabled. Let me know if it works well or if you need help installing it 🙏🏻

**Comment by Kodehawa** [comment]
> https://www.dropbox.com/scl/fi/kk0sn6y6s2r99yxc90r71/wine-osu-tkg-9.0-rc3-x86_64.tar.xz?rlkey=wq7cf2amf3fs3sbe5ib92c3sz&dl=0
> 
> Here's 9.0-rc3 with Staging and TKG patches + Wayland enabled. Let me know if it works well or if you need help installing it 🙏🏻

Hello! I imagine I have to unpack it somewhere, where would that be?

Also, happy new year :tada:

**Comment by NelloKudo** [comment]
Happy new year for you as well!! 🥳 

Anyways yep, it goes as far as replacing the `wine-osu` folder in ~/.local/share/osuconfig with the one in the package. Quick way to do that:

```
rm -rf ~/.local/share/osuconfig/wine-osu
wget -O wine-osu-tkg-9.0-rc3-x86_64.tar.xz https://www.dropbox.com/scl/fi/kk0sn6y6s2r99yxc90r71/wine-osu-tkg-9.0-rc3-x86_64.tar.xz?rlkey=wq7cf2amf3fs3sbe5ib92c3sz&dl=0
tar -xf wine-osu-tkg-9.0-rc3-x86_64.tar.xz
mv wine-osu ~/.local/share/osuconfig
```

**Comment by Kodehawa** [comment]
![imagen](https://github.com/NelloKudo/osu-winello/assets/20606963/e174fdb3-59ba-44f3-a3d5-f345e82ed17b)

Yeah seems to be broken. Tried using Vulkan too (force OpenGL-to-Vulkan, aka zink, which works fine in osu) and it didn't work either. Oh well. I wonder if it'll work better as they add more stuff to it.

**Comment by SrIzan10** [comment]
can you send the build again please?

**Comment by NelloKudo** [comment]
> can you send the build again please?

The builds the script uses by default are already built with Wayland (up to Wine 9.0). Default OpenGL doesn’t launch the game, using compatibility mode might actually get it working.

**Comment by SrIzan10** [comment]
So if I understood correctly, latest wine-builder builds should have wayland support right?
