### ISSUE TITLE
winestreamproxy 

### ISSUE THREAD

**Issue by AnimeWaifuGirl** [NelloKudo/osu-winello#63]
hey! the wineHQ update version 9.2 brake the osu rich presence function aka winestreamproxy wont to start!

**Comment by NelloKudo** [comment]
Hello! Actually, the script is still on 9.0-rc1, so if you’ve been using the one the script provides itself then you should have no problems at all with it. 

If Rich Presence’s not working for you, how have you installed Discord? Flatpak or repositories?
