### ISSUE TITLE
unable to create/edit beatmaps

### ISSUE THREAD

**Issue by JizzyOnGithub** [NelloKudo/osu-winello#68]
whenever I save a beatmap I get: 
![screenshot270](https://github.com/NelloKudo/osu-winello/assets/70417158/f09a40ff-9ed5-4ac0-8c1a-cd2441776179)

**Comment by NelloKudo** [comment]
Assuming you’re running osu! from another drive (I can read media in the path shown in the screenshot), make sure you have write permissions on that, as it’s likely the reason you can’t save stuff on it xd

If you use that disk on Windows, make sure you disable fast startup on it. Also make sure you mounted your disk correctly like shown [here](https://github.com/ValveSoftware/Proton/wiki/Using-a-NTFS-disk-with-Linux-and-Windows)
