### ISSUE TITLE
package steam-installer (really need help pls)

### ISSUE THREAD

**Issue by 92stan** [NelloKudo/osu-winello#69]
![Screenshot 2024-04-17 3 50 25 AM](https://github.com/NelloKudo/osu-winello/assets/167247932/d51c658b-8b46-4774-a1a8-7cd4215f1bb2)

**Comment by NelloKudo** [comment]
Assuming you're on debian, edit osu-winello.sh with whatever text editor (like Visual Studio or whatever), go to line 194 and replace `steam-installer` with `steam`, check if that does the trick

**Comment by 92stan** [comment]
yes, I'm on debian. I'm new to this, havent used linux before. How do I go to line 194?

**Comment by 92stan** [comment]
I used the nano command then ctrl+/ to go to line 194 edited the steam-installer to steam, now this shows. I actually don't know if I did anything right or wrong.

![Screenshot 2024-04-17 5 06 49 AM](https://github.com/NelloKudo/osu-winello/assets/167247932/3217cfa2-9ac4-487c-a450-76619bbb472d)

**Comment by NelloKudo** [comment]
I guess the script is not installing steam for some strange reason. I can probably help more on discord, but still yeah we’re stuck until we get steam to install 🥲

**Comment by 92stan** [comment]
ah sucks, what's your discord server or just pm?

**Comment by NelloKudo** [comment]
My discord is marshnello, feel free to write me there. Also yeah, the steam from Valve is needed on Debian to pull some important libraries needed for the game to run properly 🥲

**Comment by 92stan** [comment]
okay really hopefull now, I got steam to install now I'm installing osu again but the eta of the download just keeps incrasing  0.0

![Screenshot 2024-04-17 6 02 54 AM](https://github.com/NelloKudo/osu-winello/assets/167247932/80345200-a9e9-4aab-bf39-b7ff95a86a71)

**Comment by 92stan** [comment]
okay it was just my internet, now this problem 

![Screenshot 2024-04-17 6 17 32 AM](https://github.com/NelloKudo/osu-winello/assets/167247932/24c47d87-b650-4c1a-bf10-b9c38233033e)

**Comment by NelloKudo** [comment]
Should be working as of latest commit!
