### ISSUE TITLE
Recognizing wrong os

### ISSUE THREAD

**Issue by Deaddnee** [NelloKudo/osu-winello#71]
![image](https://github.com/NelloKudo/osu-winello/assets/141462579/09245f3b-e841-4a1c-8957-843e3169612c)
The thing is..
![image](https://github.com/NelloKudo/osu-winello/assets/141462579/8f98b7b7-a838-4e97-a3e7-f62d4e715e2e)
I'm not running arch

But maybe it's the fault of pacman.
Your choice.
______________
-Dnee~3

**Comment by NelloKudo** [comment]
The script finds `pacman` as a suitable command and therefore thinks it is on Arch, that's probably because Kali has some command related to it doing something else (?) haven't really used it myself as it's not a distro you should use for gaming, so you're on your own there. I'd recommend trying running the script with `./osu-winello.sh --no-deps` and install these packages yourself before running it:

- `wget`,`p7zip`,`zenity`
- Wine dependencies as listed here: https://github.com/lutris/docs/blob/master/WineDependencies.md
- Drivers as listed here: https://github.com/lutris/docs/blob/master/InstallingDrivers.md

I think Kali uses apt so you should follow the instructions for that (?) but again idk sooo good luck xD

**Comment by Deaddnee** [comment]
worked, closing this.
THX :D !!
Note: wine will spout an error([the link provided](https://learn.microsoft.com/en-us/dotnet/framework/install/application-not-started?version=(null)&processName=rundll32.exe&platform=0009&osver=6&isServer=0&shimver=4.0.30319.0)) , just close the error window and let it go on.
_____________
-Dnee~3
The outcome:
`┌──(deaddnee㉿deaddneexdedsec)-[~/osu-winello]
└─$ ./osu-winello.sh --no-deps
Winello: Welcome to the script! Follow it to install osu! 8)
Winello: Checking for internet connection..
Winello: --no-deps found, skipping dependencies..
Winello: Installing game script:
Winello: Installing icons:
Winello: Installing .desktop:
[Desktop Entry]
Name=osu!
Comment=osu! - Rhythm is just a *click* away!
Type=Application
Exec=/home/deaddnee/.local/bin/osu-wine %U
Icon=/home/deaddnee/.local/share/icons/osu-wine.png
Terminal=false
Categories=Wine;Game;
Winello: Installing wine-osu:
--2024-05-13 22:24:58--  https://github.com/NelloKudo/WineBuilder/releases/download/wine-osu-protonGE-9-4/wine-osu-protonGE-9-4-x86_64.tar.xz
Resolving github.com (github.com)... 140.82.112.4
Connecting to github.com (github.com)|140.82.112.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://objects.githubusercontent.com/github-production-release-asset-2e65be/521706693/0c5c27f8-935e-4def-a35e-66781786e90f?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20240514%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240514T032457Z&X-Amz-Expires=300&X-Amz-Signature=b8ed6c2e7633cd617652be498c1bdec44d0508ceda7a60f7a7e4a33b51948fc1&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=521706693&response-content-disposition=attachment%3B%20filename%3Dwine-osu-protonGE-9-4-x86_64.tar.xz&response-content-type=application%2Foctet-stream [following]
--2024-05-13 22:24:58--  https://objects.githubusercontent.com/github-production-release-asset-2e65be/521706693/0c5c27f8-935e-4def-a35e-66781786e90f?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20240514%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240514T032457Z&X-Amz-Expires=300&X-Amz-Signature=b8ed6c2e7633cd617652be498c1bdec44d0508ceda7a60f7a7e4a33b51948fc1&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=521706693&response-content-disposition=attachment%3B%20filename%3Dwine-osu-protonGE-9-4-x86_64.tar.xz&response-content-type=application%2Foctet-stream
Resolving objects.githubusercontent.com (objects.githubusercontent.com)... 185.199.110.133, 185.199.109.133, 185.199.111.133, ...
Connecting to objects.githubusercontent.com (objects.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 60906092 (58M) [application/octet-stream]
Saving to: ‘/tmp/wine-osu-9.4.0-x86_64.pkg.tar.xz’

/tmp/wine-osu-9.4.0-x86_64.pkg.tar.xz  100%[============================================================================>]  58.08M  21.3MB/s    in 2.7s    

2024-05-13 22:25:01 (21.3 MB/s) - ‘/tmp/wine-osu-9.4.0-x86_64.pkg.tar.xz’ saved [60906092/60906092]

Winello: Installing script copy for updates..
Cloning into '/home/deaddnee/.local/share/osuconfig/update'...
remote: Enumerating objects: 601, done.
remote: Counting objects: 100% (173/173), done.
remote: Compressing objects: 100% (40/40), done.
remote: Total 601 (delta 155), reused 136 (delta 133), pack-reused 428
Receiving objects: 100% (601/601), 250.69 KiB | 1.17 MiB/s, done.
Resolving deltas: 100% (274/274), done.
--2024-05-13 22:25:12--  https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 836601 (817K) [text/plain]
Saving to: ‘/home/deaddnee/.local/share/osuconfig/winetricks’

/home/deaddnee/.local/share/osuconfig/ 100%[============================================================================>] 816.99K  --.-KB/s    in 0.04s   

2024-05-13 22:25:13 (18.4 MB/s) - ‘/home/deaddnee/.local/share/osuconfig/winetricks’ saved [836601/836601]

Winello: Configuring osu! folder:
Winello: Where do you want to install the game?: 
          1 - Default path (~/.local/share/osu-wine)
          2 - Custom path
Winello: Choose your option: 1
Winello: Skipping..
Winello: Configuring osu-mime and osu-handler:
--2024-05-13 22:25:50--  https://aur.archlinux.org/cgit/aur.git/snapshot/osu-mime.tar.gz
Resolving aur.archlinux.org (aur.archlinux.org)... 95.216.144.15, 2a01:4f9:c010:50::1
Connecting to aur.archlinux.org (aur.archlinux.org)|95.216.144.15|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/x-gzip]
Saving to: ‘/tmp/osu-mime.tar.gz’

/tmp/osu-mime.tar.gz                       [ <=>                                                                         ]   1.71K  --.-KB/s    in 0s      

2024-05-13 22:25:51 (34.4 MB/s) - ‘/tmp/osu-mime.tar.gz’ saved [1754]

--2024-05-13 22:25:52--  https://github.com/NelloKudo/osu-winello/raw/main/stuff/osu-handler-wine
Resolving github.com (github.com)... 140.82.114.3
Connecting to github.com (github.com)|140.82.114.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/NelloKudo/osu-winello/main/stuff/osu-handler-wine [following]
--2024-05-13 22:25:52--  https://raw.githubusercontent.com/NelloKudo/osu-winello/main/stuff/osu-handler-wine
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.111.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 18592 (18K) [application/octet-stream]
Saving to: ‘/home/deaddnee/.local/share/osuconfig/osu-handler-wine’

/home/deaddnee/.local/share/osuconfig/ 100%[============================================================================>]  18.16K  --.-KB/s    in 0s      

2024-05-13 22:25:52 (41.8 MB/s) - ‘/home/deaddnee/.local/share/osuconfig/osu-handler-wine’ saved [18592/18592]

[Desktop Entry]
Type=Application
Name=osu!
MimeType=application/x-osu-skin-archive;application/x-osu-replay;application/x-osu-beatmap-archive;
Exec=/home/deaddnee/.local/share/osuconfig/osu-handler-wine %f
NoDisplay=true
StartupNotify=true
Icon=/home/deaddnee/.local/share/icons/osu-wine.png
[Desktop Entry]
Type=Application
Name=osu!
MimeType=x-scheme-handler/osu;
Exec=/home/deaddnee/.local/share/osuconfig/osu-handler-wine %u
NoDisplay=true
StartupNotify=true
Icon=/home/deaddnee/.local/share/icons/osu-wine.png
Winello: Configuring Wineprefix:
--2024-05-13 22:25:53--  https://gitlab.com/NelloKudo/osu-winello-prefix/-/raw/master/osu-winello-prefix.7z
Resolving gitlab.com (gitlab.com)... 172.65.251.78, 2606:4700:90:0:f22e:fbec:5bed:a9b9
Connecting to gitlab.com (gitlab.com)|172.65.251.78|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 288858670 (275M) [application/octet-stream]
Saving to: ‘/home/deaddnee/.winellotmp/WINE.win32.7z’

/home/deaddnee/.winellotmp/WINE.win32. 100%[============================================================================>] 275.48M  22.8MB/s    in 12s     

2024-05-13 22:26:05 (22.5 MB/s) - ‘/home/deaddnee/.winellotmp/WINE.win32.7z’ saved [288858670/288858670]


7-Zip 23.01 (x64) : Copyright (c) 1999-2023 Igor Pavlov : 2023-06-20
 64-bit locale=C.UTF-8 Threads:4 OPEN_MAX:1024

Scanning the drive for archives:
1 file, 288858670 bytes (276 MiB)    

Extracting archive: /home/deaddnee/.winellotmp/WINE.win32.7z
--
Path = /home/deaddnee/.winellotmp/WINE.win32.7z
Type = 7z
Physical Size = 288858670
Headers Size = 39994
Method = LZMA2:24 BCJ
Solid = +
Blocks = 2

Everything is Ok                                                                                                                                           

Folders: 861
Files: 3564
Size:       1409478749
Compressed: 288858670
Winello: Installing fonts...
--2024-05-13 22:27:00--  https://github.com/YourRandomGuy/ttf-ms-win10/archive/refs/heads/build.zip
Resolving github.com (github.com)... 140.82.114.4
Connecting to github.com (github.com)|140.82.114.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/YourRandomGuy/ttf-ms-win10/zip/refs/heads/build [following]
--2024-05-13 22:27:00--  https://codeload.github.com/YourRandomGuy/ttf-ms-win10/zip/refs/heads/build
Resolving codeload.github.com (codeload.github.com)... 140.82.112.9
Connecting to codeload.github.com (codeload.github.com)|140.82.112.9|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/zip]
Saving to: ‘/tmp/fonts.zip’

/tmp/fonts.zip                             [                                                                  <=>        ] 192.24M  11.6MB/s    in 18s     

2024-05-13 22:27:18 (10.8 MB/s) - ‘/tmp/fonts.zip’ saved [201582587]


7-Zip 23.01 (x64) : Copyright (c) 1999-2023 Igor Pavlov : 2023-06-20
 64-bit locale=C.UTF-8 Threads:4 OPEN_MAX:1024

Scanning the drive for archives:
1 file, 201582587 bytes (193 MiB)

Extracting archive: /tmp/fonts.zip
--
Path = /tmp/fonts.zip
Type = zip
Physical Size = 201582587
Comment = 7296febd01671c13041444966518b80dc9852e21

Everything is Ok                                 

Folders: 1
Files: 149
Size:       355839876
Compressed: 201582587
Winello: Adding fonts to Wineprefix (please wait a bit!)
Winello: (Answer whatever to the Wine prompt, it is NOT an error!)
wineserver: using server-side synchronization.
002c:fixme:winediag:loader_init wine-staging 9.0 is a testing version containing experimental patches.
002c:fixme:winediag:loader_init Please mention your exact version when filing bug reports on winehq.org.
0088:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0088:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0088:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0088:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0134:err:ole:apartment_add_dll couldn't find function DllGetClassObject in L"C:\\windows\\system32\\uiautomationcore.dll"
0134:err:ole:com_get_class_object no class object {e22ad333-b25f-460c-83d0-0581107395c9} could be created for context 0x1
0134:err:tabtip:add_uia_event_handler Failed to create IUIAutomation interface, hr 0x800401f8
0140:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 00006FFFFFB425B7, 28) stub
0140:err:advpack:create_tmp_ini_file Can't get temp ini file path
0140:err:mshtml:register_server RegInstall failed: 80004005
0140:err:advpack:create_tmp_ini_file Can't get temp ini file path
0150:err:advpack:create_tmp_ini_file Can't get temp ini file path
0160:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
0160:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 78323241, 28) stub
0160:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 77B509AD, 28) stub
0160:err:advpack:create_tmp_ini_file Can't get temp ini file path
0160:err:mshtml:register_server RegInstall failed: 80004005
0160:err:advpack:create_tmp_ini_file Can't get temp ini file path
0168:err:advpack:create_tmp_ini_file Can't get temp ini file path
wine: configuration in L"/home/deaddnee/.local/share/wineprefixes/osu-wineprefix" has been updated.
wineserver: using server-side synchronization.
002c:fixme:winediag:loader_init wine-staging 9.0 is a testing version containing experimental patches.
002c:fixme:winediag:loader_init Please mention your exact version when filing bug reports on winehq.org.
002c:fixme:wineboot:read_tsc_frequency TSC frequency calibration failed, unstable TSC?time0 13360130948380335200 ns, time1 13360130948381408300 ns
002c:fixme:wineboot:read_tsc_frequency tsc2 - tsc0 3650198, tsc3 - tsc1 3657102
002c:fixme:wineboot:read_tsc_frequency freq0 3401545056 Hz, freq2 3407978753 Hz, error 1891 ppm
0094:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0094:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0094:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0094:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
reg: The operation completed successfully
reg: The operation completed successfully
reg: The operation completed successfully
Winello: Configuring Winestreamproxy (Discord RPC)
--2024-05-13 22:29:10--  https://github.com/openglfreak/winestreamproxy/releases/download/v2.0.3/winestreamproxy-2.0.3-amd64.tar.gz
Resolving github.com (github.com)... 140.82.114.4
Connecting to github.com (github.com)|140.82.114.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://objects.githubusercontent.com/github-production-release-asset-2e65be/248621830/0a0220c4-a78b-426a-8c41-e4276de8ff14?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20240514%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240514T032911Z&X-Amz-Expires=300&X-Amz-Signature=ae90b98790965ac4f53f8ea6187009b3afa0b29891e9b38df789fd52e2a26ef3&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=248621830&response-content-disposition=attachment%3B%20filename%3Dwinestreamproxy-2.0.3-amd64.tar.gz&response-content-type=application%2Foctet-stream [following]
--2024-05-13 22:29:11--  https://objects.githubusercontent.com/github-production-release-asset-2e65be/248621830/0a0220c4-a78b-426a-8c41-e4276de8ff14?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20240514%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240514T032911Z&X-Amz-Expires=300&X-Amz-Signature=ae90b98790965ac4f53f8ea6187009b3afa0b29891e9b38df789fd52e2a26ef3&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=248621830&response-content-disposition=attachment%3B%20filename%3Dwinestreamproxy-2.0.3-amd64.tar.gz&response-content-type=application%2Foctet-stream
Resolving objects.githubusercontent.com (objects.githubusercontent.com)... 185.199.108.133, 185.199.111.133, 185.199.109.133, ...
Connecting to objects.githubusercontent.com (objects.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 213654 (209K) [application/octet-stream]
Saving to: ‘/tmp/winestreamproxy-2.0.3-amd64.tar.gz’

/tmp/winestreamproxy-2.0.3-amd64.tar.g 100%[============================================================================>] 208.65K  --.-KB/s    in 0.03s   

2024-05-13 22:29:11 (6.99 MB/s) - ‘/tmp/winestreamproxy-2.0.3-amd64.tar.gz’ saved [213654/213654]

Winello: Downloading osu!
--2024-05-13 22:29:13--  http://m1.ppy.sh/r/osu!install.exe
Resolving m1.ppy.sh (m1.ppy.sh)... 162.243.70.14
Connecting to m1.ppy.sh (m1.ppy.sh)|162.243.70.14|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4508616 (4.3M) [application/octet-stream]
Saving to: ‘/home/deaddnee/.local/share/osu-wine/osu!/osu!.exe’

/home/deaddnee/.local/share/osu-wine/o 100%[============================================================================>]   4.30M  4.97MB/s    in 0.9s    

2024-05-13 22:29:14 (4.97 MB/s) - ‘/home/deaddnee/.local/share/osu-wine/osu!/osu!.exe’ saved [4508616/4508616]

Winello: Installation is completed! Run 'osu-wine' to play osu!
Winello: WARNING: If 'osu-wine' doesn't work, just close and relaunch your terminal.
`
