### ISSUE TITLE
Script trying to install files in a non-directory

### ISSUE THREAD

**Issue by YumisWorld** [NelloKudo/osu-winello#72]
The script is trying to touch in a directory that doesn't exist. This could be because my user-name and home folder have different names.

Bash outputs: ```mkdir: cannot create directory ‘/home/yumiko’: Permission denied
touch: cannot touch '/home/yumiko/.bashrc': No such file or directory
./osu-winello.sh: line 107: /home/yumiko/.bashrc: No such file or directory```, when my actual home folder is located in ``/home/lexi``. This results in the game being unable to install.

**Comment by NelloKudo** [comment]
That is because the script is supposed to read `$USER` from bash and use its home as the default location.
An easy workaround you can try is simply setting the user in the same terminal before launching the script with:
`export USER=yourusername`

**Comment by YumisWorld** [comment]
This has worked, the script installed and created files in the right directories now.
