### ISSUE TITLE
Is the offset actually necessary?

### ISSUE THREAD

**Issue by Malternative3772** [NelloKudo/osu-winello#73]
So I've been noticing that I with the recommended -35 offset, I pretty consistently hit the notes early, a problem that goes away when just setting it to zero... Could this issue within wine possibly have been fixed?
I'm running Arch with all the relevant packages updated to the latest version.

**Comment by Sclafus** [comment]
Well, it is a recommendation, for me -25 is working pretty well.
There are way too many variables at play to give just a number that will work for everyone (kernel, pulseaudio/pipewire/alsa/whatever, sound card, etc)
Just use what works best for you!

**Comment by PhoenixEmik** [comment]
This offset value depends on your configurations. For me the offset is -30 that works well.
If zero offset works for you, then just let it be zero.
