### ISSUE TITLE
artix/other arch based systems with different repo names

### ISSUE THREAD

**Issue by kreciorek** [NelloKudo/osu-winello#76]
when i tried to install, it recognized it as arch and i didint think much of it, but it was trying to add multi-lib repo when on artix its lib32.
it looks like this 
Artix | Arch
    -- | --
system | core
world | extra
lib32 | multilib
so basically it fails since theres no repo as multilib.
in fact u can get arch repos but they dont work for some reason.

**Comment by NelloKudo** [comment]
I guess I'll need to add a check for Artix as well. Thanks for noticing!
