### ISSUE TITLE
Problem Involving wine-staging and wine-cachyos

### ISSUE THREAD

**Issue by Tixctes** [NelloKudo/osu-winello#79]
:: wine-staging-9.8-1 and wine-cachyos-2:9.0.20240619-1 are in conflict (wine). Remove wine-cachyos? [y/N] 
error: unresolvable package conflicts detected
error: failed to prepare transaction (conflicting dependencies)
:: wine-staging-9.8-1 and wine-cachyos-2:9.0.20240619-1 are in conflict
Script failed: Some libraries didn't install for some reason, check pacman or your connection
Reverting install...:
Reverting done, try again with ./osu-winello.sh

**Comment by NelloKudo** [comment]
I guess I'll add a check for cachyos as well 👍🏻
