### ISSUE TITLE
osu! goes black in Hyprland when using windows+left arrow to go to my left monitor

### ISSUE THREAD

**Issue by yorunoken** [NelloKudo/osu-winello#80]
osu! doesn't let me out of the window if it's not fullscreen, so when I use windows+left arrow to my left monitor, it just goes black and there's no way to recover it
video: https://yorunoken.s-ul.eu/bHKTVgPO

**Comment by NelloKudo** [comment]
Isn’t there a setting about confining cursor in osu? Try setting that to never, it may fix it even with fullscreen enabled

**Comment by NelloKudo** [comment]
What if you use fullscreen without the minimize on alt-tab? Would it still result in a black window?

**Comment by yorunoken** [comment]
I have no idea how but I fixed this, might've been my driver
