### ISSUE TITLE
Poor performance

### ISSUE THREAD

**Issue by greatelmo** [NelloKudo/osu-winello#82]
I'm using Mint 22 XFCE and moving the mouse cursor lags the game out and is damn near unplayable. Also unplayable performance anyways.

Windows never did this. Also how do I import my songs that I've saved from Windows into Linux?

**Comment by Sclafus** [comment]
[Moving Skins and Songs from Windows](https://github.com/NelloKudo/osu-winello/wiki/Moving-skins-songs-from-Windows)
Please check that your graphics card drivers are installed, especially if you have an nvidia card. Also check [Gamemode](https://github.com/NelloKudo/osu-winello/wiki/(Possibly)-optimize-your-game:-Gamemode)

**Comment by greatelmo** [comment]
Thanks but I already went back to Windows 7. 

I have AMD Radeon HD 6310 integrated graphics
