### ISSUE TITLE
install script enables lib32 repo in arch

### ISSUE THREAD

**Issue by k557osuman** [NelloKudo/osu-winello#83]
install script is incorrectly enables lib32 repo in Arch Linux, leading to pacman sync errors

pls fix

![screen143](https://github.com/user-attachments/assets/31c80c8b-494c-4d02-8a44-8b32d595e9da)

**Comment by NelloKudo** [comment]
I tested on Arch myself and it's not supposed to be finding lib32 in your pacman.conf tho.
Can you send me a screenshot of how /etc/pacman.conf looks in your case?

**Comment by k557osuman** [comment]
hello, sorry for the late reply. got internet issues :(
![2024-08-05 14-24-37](https://github.com/user-attachments/assets/bab786e9-b3eb-48de-af2e-93e456ca446a)
this is what happens when i do a fresh install of osu-winello again

**Comment by k557osuman** [comment]
this is what my pacman.conf looks like after running the script
![image](https://github.com/user-attachments/assets/14c03d3d-c40d-43ce-bacf-0c57d8fc52c0)

**Comment by k557osuman** [comment]
closing this because i switched to a new distro (non-Arch)
