### ISSUE TITLE
Client is squished on full-screen mode

### ISSUE THREAD

**Issue by spiralw** [NelloKudo/osu-winello#9]
![Screenshot from 2022-09-24 14-23-32](https://user-images.githubusercontent.com/64013111/192113329-ea8c08fe-5fde-4a23-a405-31b9eebe6ada.png)

disabling full-screen mode fixes the issue (the client appears to remain in full-screen anyway)

logs: https://gist.github.com/spiralw/bb607ea3070184c01136c30e2152d526

**Comment by NelloKudo** [comment]
now this is strange lol, could you tell me what distro/DE are you on? i’ll try myself

**Comment by spiralw** [comment]
I'm on PopOS which already installs latest proprietary drivers. the logs say to install nouveau, but I can't do that without breaking my install

**Comment by spiralw** [comment]
also, probably not related, the client is extremely laggy while switching between pages, and the UI is only usable if I set the frame limiter to `Unlimited (gameplay)`. fwiw, while actually playing a map the client is completely usable no matter what settings I choose

**Comment by spiralw** [comment]
i just played a full map, the client took ~1 minute to go from ending the map (music stops and screen turns black) to showing the score screen, and then it started spamming my logs with this

![Screenshot from 2022-09-24 16-46-42](https://user-images.githubusercontent.com/64013111/192118276-646de2d8-2f87-4d91-a9ce-c455bd1a8923.png)

**Comment by spiralw** [comment]
osu-wine just crashed with this error:

```
0748:fixme:rawinput:NtUserRegisterRawInputDevices Unhandled flags 0x200 for device 0.
0050:err:seh:NtRaiseException Unhandled exception code c0000005 flags 0 addr 0x682d1c1b
```

 (just posting updates from me messing with it, i'm still mostly on windows for now since this is not really playable)

**Comment by NelloKudo** [comment]
> i just played a full map, the client took ~1 minute to go from ending the map (music stops and screen turns black) to showing the score screen, and then it started spamming my logs with this
> 
> ![Screenshot from 2022-09-24 16-46-42](https://user-images.githubusercontent.com/64013111/192118276-646de2d8-2f87-4d91-a9ce-c455bd1a8923.png)

Just rocked a Pop_OS vm and haven't really faced any of those problems:
https://streamable.com/0mdxk8 (yeah enjoy my 2am spotify xD)

Could you tell me more about your setup? Not only hardware, also if you use any external monitor connected to your machine and stuff like that, sine xrandr seems to (complain about them)[https://forum.winehq.org/viewtopic.php?t=35507#p136159].

> I'm on PopOS which already installs latest proprietary drivers. the logs say to install nouveau, but I can't do that without breaking my install

Also even though Pop_OS should already ship by default NVIDIA's proprietary stuff, run the following as a backup for any possible missing library:

`sudo add-apt-repository ppa:graphics-drivers/ppa && sudo dpkg --add-architecture i386 && sudo apt update && sudo apt install -y nvidia-driver-515 libvulkan1 libvulkan1:i386`

> osu-wine just crashed with this error:
> 
> ```
> 0748:fixme:rawinput:NtUserRegisterRawInputDevices Unhandled flags 0x200 for device 0.
> 0050:err:seh:NtRaiseException Unhandled exception code c0000005 flags 0 addr 0x682d1c1b
> ```
> 
> (just posting updates from me messing with it, i'm still mostly on windows for now since this is not really playable)

This crash should be related to either compatibility mode/audio compatibility mode, please disable them as there's no reason to actually use them.

Let me know more e.e

**Comment by NelloKudo** [comment]
If what is told above does not fix those terminal logs, use this wine-osu 7.15 binary built with the usual patches + [this one]() which should get rid of your error.

You can replace it with:
```
wget https://www.dropbox.com/s/gbeqzto5o86q9k0/wine-osu-7.15.2-x86_64.tar.xz?dl=0
tar -xf wine-osu-7.15.2-x86_64.tar.xz
rm -rf ~/.local/share/osuconfig/wine-osu
cp -r wine-osu ~/.local/share/osuconfig
rm -rf wine-osu
```

**Comment by spiralw** [comment]
hey, sorry for the delay. i got some time to try this today

some details about my setup:
```
spiral@pop-os:~$ neofetch --stdout
spiral@pop-os 
------------- 
OS: Pop!_OS 22.04 LTS x86_64 
Host: Blade 15 Advanced Model (Mid 2021) - RZ09-0409 7.04 
Kernel: 5.19.0-76051900-generic 
Uptime: 3 hours, 19 mins 
Packages: 2187 (dpkg) 
Shell: bash 5.1.16 
Resolution: 3840x2160, 2560x1440, 1920x1080, 1920x1080 
DE: GNOME 42.3.1 
Terminal: gnome-terminal 
CPU: 11th Gen Intel i7-11800H (16) @ 4.600GHz 
GPU: NVIDIA GeForce RTX 3060 Mobile / Max-Q 
Memory: 7388MiB / 15815MiB
```


I tried updating drivers but that just confirmed I have the most recent ones:
```
spiral@pop-os:~$ sudo add-apt-repository ppa:graphics-drivers/ppa && sudo dpkg --add-architecture i386 && sudo apt update && sudo apt install -y nvidia-driver-515 libvulkan1 libvulkan1:i386
[...]
Adding repository.
Press [ENTER] to continue or Ctrl-c to cancel.
Adding deb entry to /etc/apt/sources.list.d/graphics-drivers-ubuntu-ppa-jammy.list
Adding disabled deb-src entry to /etc/apt/sources.list.d/graphics-drivers-ubuntu-ppa-jammy.list
Adding key to /etc/apt/trusted.gpg.d/graphics-drivers-ubuntu-ppa.gpg with fingerprint 2388FF3BE10A76F638F80723FCAE110B1118213C
[...]
nvidia-driver-515 is already the newest version (515.65.01-1pop0~1663626642~22.04~1f94f41).
libvulkan1 is already the newest version (1.3.204.1-2).
libvulkan1 set to manually installed.
libvulkan1:i386 is already the newest version (1.3.204.1-2).
libvulkan1:i386 set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 33 not upgraded.
```

disabling compatibility mode doesn't work; the client restarts and compatibility mode is still enabled.

here's [a video](https://www.youtube.com/watch?v=lrPM14vgKmY) of me trying to run the client - ignore the, like, two minutes in the middle where trying to fullscreen the game broke my display config and i had to set it up again
there's a timer on the top right so you can see how long it takes to do anything

**Comment by spiralw** [comment]
I just tried your patched wine version and that did fix most of the issues! there's still a lot of frame drops while playing a map, and the client does take ~2min to boot up still, but otherwise this is much more usable.

**Comment by NelloKudo** [comment]
mhh, I’m actually starting to think this is related to NVIDIA Optimus, do you happen to have that? If so, try launching osu! with:

`prime-run osu-wine`

**Comment by spiralw** [comment]
I'm not running Optimus - my laptop allows me to fully disable the iGPU and output video directly from the nvidia card.

**Comment by NelloKudo** [comment]
has any of the latest nvidia drivers updates fixed that? it shouldn’t really be a script issue anymore, I’ll release a new Wine later which might help

**Comment by NelloKudo** [comment]
Closing this as performance seems to fix after a few launches for many people on the same setup. ;)
