### ISSUE TITLE
Crash every other startup caused by spurious runtime updates

### ISSUE THREAD

**Issue by AAGaming00** [NelloKudo/osu-winello#93]
I've just installed this on my Steam Deck, the game runs fine, but every time I run osu-wine I get "Updating steamrt to latest..." and the script crashes later as the runtime no longer exists. Then the next time I get "Restoring Runtime Platform" and the game starts fine. This cycle repeats every launch.

**Comment by AAGaming00** [comment]
Reinstalling osu-winello on one of the good cycles fixed this for me, but it might still be worth looking into.

**Comment by AAGaming00** [comment]
OH IT'S TUESDAY THAT'S WHY LOL
![steam status](https://github.com/user-attachments/assets/82db72d0-2c7d-400a-8cca-f44362c5d8c1)

**Comment by NelloKudo** [comment]
LOL THAT'S A FUNNY ONE forgot i even had to consider Steam now. Thanks for the heads-up!
