### ISSUE TITLE
this is taking way too long

### ISSUE THREAD

**Issue by DoriteLover** [NelloKudo/osu-winello#94]

**Comment by DoriteLover** [comment]
sorry i accidiental hit enter but sooo, it is taking 10hr to load which is so so so long and i cant wait that long because i have to abort the progress and i have to RELOAD at 0%
![image](https://github.com/user-attachments/assets/d6194036-de6a-4949-9091-1cd4e9905046)

**Comment by DoriteLover** [comment]
im located in Asia and my internet is 150+ mbps so I guess thats why? I think winellow server is in somewhat America I think? I'm an idiot don't blame me

**Comment by Sclafus** [comment]
Hi, can you try to download manually the prefix from this link? https://gitlab.com/NelloKudo/osu-winello-prefix/-/blob/master/osu-winello-prefix.tar.xz
If the download speed for this file is normal from your browser, try again. If it still does not work, it may indicate some issues on your system.
There is no such thing as winello server btw

**Comment by NelloKudo** [comment]
Well, 13 minutes don’t sound like a lot tbh. 
If you still have issues downloading it from the script, let it download from the browser, then:
- Create `~/.local/share/wineprefixes`
- Extract the package you downloaded and copy the `osu-umu` folder there
- Rename `osu-umu` to `osu-wineprefix`

Then run Winello, and when it prompts for reinstalling the Wineprefix, just say no. Let us know 🥳

**Comment by DoriteLover** [comment]
update: i got it but freezing 
![image](https://github.com/user-attachments/assets/3568298b-86a3-4c63-b76b-58b898a74f4f)

**Comment by DoriteLover** [comment]
update #2: it is doing thing again, if sucess will close with new comment

**Comment by NelloKudo** [comment]
Oh it’s not freezing, it’s just extracting it. Give it some time 🏃🏻‍♂️

**Comment by DoriteLover** [comment]
realpuphan@puphanlinux:~/osu-winello/osu-winello$ osu-wine
ProtonFixes[19228] INFO: Running protonfixes
ProtonFixes[19228] INFO: Running checks
ProtonFixes[19228] INFO: All checks successful
ProtonFixes[19228] INFO: Non-steam game UNKNOWN (osu-wine-umu)
ProtonFixes[19228] INFO: No store specified, using UMU database
ProtonFixes[19228] INFO: Using global defaults for UNKNOWN (osu-wine-umu)
ProtonFixes[19228] INFO: Non-steam game UNKNOWN (osu-wine-umu)
ProtonFixes[19228] INFO: No store specified, using UMU database
ProtonFixes[19228] INFO: No global protonfix found for UNKNOWN (osu-wine-umu)
Proton: /home/realpuphan/.local/share/osu-wine/osu!/osu!.exe
Proton: Executable a unix path, launching with /unix option.
fsync: up and running.
libGL error: MESA-LOADER: failed to open radeonsi: /usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu/dri/radeonsi_dri.so: wrong ELF class: ELFCLASS64 (search paths /usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu/dri)
libGL error: failed to load driver: radeonsi
libGL error: MESA-LOADER: failed to open swrast: /usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu/dri/swrast_dri.so: wrong ELF class: ELFCLASS64 (search paths /usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu/dri)
libGL error: failed to load driver: swrast
X Error of failed request:  GLXBadContext
  Major opcode of failed request:  149 (GLX)
  Minor opcode of failed request:  6 (X_GLXIsDirect)
  Serial number of failed request:  490
  Current serial number in output stream:  489
realpuphan@puphanlinux:~/osu-winello/osu-winello$

**Comment by NelloKudo** [comment]
I don’t know what distro is that, but make sure you install drivers like told in the install guide, should fix it

**Comment by DoriteLover** [comment]
> I don’t know what distro is that, but make sure you install drivers like told in the install guide, should fix it

kde neon btw (mistake unbutu)

**Comment by DoriteLover** [comment]
update: my pc crashed. can abort progress and do this tomorrow, also I already install amd driver (deb format) with the discover app. but it is showing nothing (even apps for display color gamma and resloution)

**Comment by NelloKudo** [comment]
> update: my pc crashed. can abort progress and do this tomorrow, also I already install amd driver (deb format) with the discover app. but it is showing nothing (even apps for display color gamma and resloution)

There's not such thing as AMD proprietary drivers on Linux, you can install packages needed for the game to run from this link: https://github.com/lutris/docs/blob/master/InstallingDrivers.md

**Comment by DoriteLover** [comment]
hi again owner, driver problem read the older comment btw

**Comment by DoriteLover** [comment]
realpuphan@puphanlinux:~$ osu-wine
ProtonFixes[5351] INFO: Running protonfixes
ProtonFixes[5351] INFO: Running checks
ProtonFixes[5351] INFO: All checks successful
ProtonFixes[5351] INFO: Non-steam game UNKNOWN (osu-wine-umu)
ProtonFixes[5351] INFO: No store specified, using UMU database
ProtonFixes[5351] INFO: Using global defaults for UNKNOWN (osu-wine-umu)
ProtonFixes[5351] INFO: Non-steam game UNKNOWN (osu-wine-umu)
ProtonFixes[5351] INFO: No store specified, using UMU database
ProtonFixes[5351] INFO: No global protonfix found for UNKNOWN (osu-wine-umu)
Proton: /home/realpuphan/.local/share/osu-wine/osu!/osu!.exe
Proton: Executable a unix path, launching with /unix option.
fsync: up and running.
libGL error: MESA-LOADER: failed to open radeonsi: /usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu/dri/radeonsi_dri.so: wrong ELF class: ELFCLASS64 (search paths /usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu/dri)
libGL error: failed to load driver: radeonsi
libGL error: MESA-LOADER: failed to open swrast: /usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu/dri/swrast_dri.so: wrong ELF class: ELFCLASS64 (search paths /usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu/dri)
libGL error: failed to load driver: swrast
X Error of failed request:  GLXBadContext
  Major opcode of failed request:  149 (GLX)
  Minor opcode of failed request:  6 (X_GLXIsDirect)
  Serial number of failed request:  510
  Current serial number in output stream:  509
realpuphan@puphanlinux:~$

**Comment by NelloKudo** [comment]
Should be fixed anyways with this: https://github.com/NelloKudo/osu-winello/commit/c5908f29b14c52acfd356225193994375718aff7
