### ISSUE TITLE
winello-umu will create the osu! config file as osu!.steamuser.cfg

### ISSUE THREAD

**Issue by PhoenixEmik** [NelloKudo/osu-winello#95]
I think it is supposed to have such a behavior.
But if there is already an osu! installation, can we make "osu!.steamuser.cfg" as a symbolic link to the existing osu! config file "osu!.$USER.cfg"?

Example command (cautious with the exclamation mark after 'osu'):
```bash
ln -s "osu"'!'".$USER.cfg" 'osu!.steamuser.cfg'
```

**Comment by NelloKudo** [comment]
Great advice actually! I’ll add that to the script when I’m free then. Should be pretty easy anyways ;)

**Comment by PhoenixEmik** [comment]
Maybe we should always use $USER osu! config instead of the steamuser one for better consistency.

**Comment by NelloKudo** [comment]
> Maybe we should always use $USER osu! config instead of the steamuser one for better consistency.

Thought about that too, but i’d need to check whether osu!’d just overwrite that file when first launched. I mean, I could also just patch proton to use the actual username instead of steamuser, but I’m afraid it’d cause other issues in umu or related :// will consider that though.

**Comment by PhoenixEmik** [comment]
Just did a quick test.
osu! overwrites osu!.steamuser.cfg when the game exits, even if the steamuser cfg has been turned into a symbolic link.
And if there is a "steamuser cfg -> actual username cfg" link, the username cfg is removed automatically at the same time.
So the symbolic link method doesn't work...

**Comment by NelloKudo** [comment]
Fixed by patching Proton, Wine now just uses the username as usual. 🥳 
More here if you're curious: https://github.com/whrvt/umubuilder/commit/5289903034351ff0e802c40c2a3fea001dd09693

Let me know if any other issue comes up 🙏🏻
