### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by greatelmo** [NelloKudo/osu-winello#96]
FEEL FREE TO CLOSE. REINSTALLING THE GAME WORKED FINE

**Comment by kartavkun** [comment]
Send the bin and .desktop files. 
osu-wine bin should be located in $HOME/.local/bin
osu-wine desktop should be located in $HOME/.local/share/applications 
Just open them any text editor, nano, vim, neovim, sublime text, whatever

**Comment by kartavkun** [comment]
close this issue pls
