### ISSUE TITLE
Add flag to install tosu

### ISSUE THREAD

**Issue by NoelleTGS** [NelloKudo/osu-winello#97]
[tosu](https://github.com/KotRikD/tosu) is a more recent and user-friendly memory reader than gosumemory, so it would be nice to have a way to install it.

It's compatible with everything from gosumemory so replacing gosumemory support entirely might even be an option, though I don't know how needed that is.

**Comment by NelloKudo** [comment]
I'll test and add it then, sure thing. Though I might need some time as I'd like for it to download the latest release without me needing to update it everytime (since I've seen it gets a lot of updates 🥇 )

**Comment by kartavkun** [comment]
I made PR for that 
https://github.com/NelloKudo/osu-winello/pull/98

**Comment by NoelleTGS** [comment]
Thanks for the quick work you two :grin:
