### ISSUE TITLE
Can it run w/out wine (im an idiot)

### ISSUE THREAD

**Issue by DoriteLover** [NelloKudo/osu-winello#99]
dont blame me i may get banned for this stupid issue but can it because im having a ahard time studying arch and im using archcraft rn it got less problem than kde neon on last issue because i move to lazer but for today im not letting lazer making my skill fall so first out. can i run w/out wine, how to install wine on arch, driver issue how to fix. this is all my problem. if you consider helping me thanks a lot. 

the picture is related to "driver issue how to fix"
![image](https://github.com/user-attachments/assets/eaf7d032-eb93-4b62-bb10-5c26d9260819)

**Comment by kartavkun** [comment]
You just need to connect to multilib repos
How?

So, type
 ```
sudo nano /etc/pacman.conf
```
In this file you need to find this
```
#[multilib]
#Include=/etc/pacman.d/mirrorlist
```

If these lines has #, it means they are commented and doesn't work. Just delete # in these lines, save file and the sync repos by
```
sudo pacman -Sy
```

**Comment by kartavkun** [comment]
multilib repository contains 32 bit packages and these packages located in multilib, so you need to connect multilib repos to pacman and sync repositories by -Sy flag

**Comment by DoriteLover** [comment]
now question 2, can it run w out wine

**Comment by DoriteLover** [comment]
If not then question 3 how to install wine in arch :>

**Comment by kartavkun** [comment]
> now question 2, can it run w out wine

Yeah, you can
The bin file starts osu wine own version of wine, so you don't need to install wine

**Comment by kartavkun** [comment]
> says no packages updated

You have issues with mirrorlist, but yiu can just repeat the update command

**Comment by DoriteLover** [comment]
![image](https://github.com/user-attachments/assets/1a7a7192-4336-49fd-98f5-2fe00d9d2d23)

**Comment by DoriteLover** [comment]
tysm

**Comment by kartavkun** [comment]
Are you tried another DE/WM? Another distro? Or what?
